//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for bmeCatImportCronJobDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bmeCatImportCronJobDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}mediaProcessCronJobDTO">
 *       &lt;sequence>
 *         &lt;element name="articleCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element ref="{}catalog" minOccurs="0"/>
 *         &lt;element name="catalogDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="catalogID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="catalogInfoAvailable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="catalogVersion" type="{}catalogVersionDTO" minOccurs="0"/>
 *         &lt;element name="catalogVersionName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="categoryAssignmentsCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="categoryCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="defaultCurrency" type="{}currencyDTO" minOccurs="0"/>
 *         &lt;element name="defaultCurrencyIsoCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="importAgreement" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="importBuyer" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="importLanguage" type="{}languageDTO" minOccurs="0"/>
 *         &lt;element name="importLanguageIsoCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="importSupplier" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="keywordCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="keywordType" type="{}composedTypeDTO" minOccurs="0"/>
 *         &lt;element name="localizationUpdate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="mediasMedia" type="{}bmeCatJobMediaDTO" minOccurs="0"/>
 *         &lt;element name="mimeCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="previousUpdateVersion" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="referenceMedias" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="territories" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="transactionMode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bmeCatImportCronJobDTO", propOrder = {
    "articleCount",
    "catalog",
    "catalogDate",
    "catalogID",
    "catalogInfoAvailable",
    "catalogVersion",
    "catalogVersionName",
    "categoryAssignmentsCount",
    "categoryCount",
    "defaultCurrency",
    "defaultCurrencyIsoCode",
    "importAgreement",
    "importBuyer",
    "importLanguage",
    "importLanguageIsoCode",
    "importSupplier",
    "keywordCount",
    "keywordType",
    "localizationUpdate",
    "mediasMedia",
    "mimeCount",
    "previousUpdateVersion",
    "referenceMedias",
    "territories",
    "transactionMode"
})
public class BmeCatImportCronJobDTO
    extends MediaProcessCronJobDTO
{

    protected Integer articleCount;
    protected CatalogDTO catalog;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar catalogDate;
    protected String catalogID;
    protected Boolean catalogInfoAvailable;
    protected CatalogVersionDTO catalogVersion;
    protected String catalogVersionName;
    protected Integer categoryAssignmentsCount;
    protected Integer categoryCount;
    protected CurrencyDTO defaultCurrency;
    protected String defaultCurrencyIsoCode;
    protected Boolean importAgreement;
    protected Boolean importBuyer;
    protected LanguageDTO importLanguage;
    protected String importLanguageIsoCode;
    protected Boolean importSupplier;
    protected Integer keywordCount;
    protected ComposedTypeDTO keywordType;
    protected Boolean localizationUpdate;
    protected BmeCatJobMediaDTO mediasMedia;
    protected Integer mimeCount;
    protected Integer previousUpdateVersion;
    protected Boolean referenceMedias;
    protected BmeCatImportCronJobDTO.Territories territories;
    protected String transactionMode;

    /**
     * Gets the value of the articleCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getArticleCount() {
        return articleCount;
    }

    /**
     * Sets the value of the articleCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setArticleCount(Integer value) {
        this.articleCount = value;
    }

    /**
     * Gets the value of the catalog property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogDTO }
     *     
     */
    public CatalogDTO getCatalog() {
        return catalog;
    }

    /**
     * Sets the value of the catalog property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogDTO }
     *     
     */
    public void setCatalog(CatalogDTO value) {
        this.catalog = value;
    }

    /**
     * Gets the value of the catalogDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCatalogDate() {
        return catalogDate;
    }

    /**
     * Sets the value of the catalogDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCatalogDate(XMLGregorianCalendar value) {
        this.catalogDate = value;
    }

    /**
     * Gets the value of the catalogID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalogID() {
        return catalogID;
    }

    /**
     * Sets the value of the catalogID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalogID(String value) {
        this.catalogID = value;
    }

    /**
     * Gets the value of the catalogInfoAvailable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCatalogInfoAvailable() {
        return catalogInfoAvailable;
    }

    /**
     * Sets the value of the catalogInfoAvailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCatalogInfoAvailable(Boolean value) {
        this.catalogInfoAvailable = value;
    }

    /**
     * Gets the value of the catalogVersion property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogVersionDTO }
     *     
     */
    public CatalogVersionDTO getCatalogVersion() {
        return catalogVersion;
    }

    /**
     * Sets the value of the catalogVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogVersionDTO }
     *     
     */
    public void setCatalogVersion(CatalogVersionDTO value) {
        this.catalogVersion = value;
    }

    /**
     * Gets the value of the catalogVersionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalogVersionName() {
        return catalogVersionName;
    }

    /**
     * Sets the value of the catalogVersionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalogVersionName(String value) {
        this.catalogVersionName = value;
    }

    /**
     * Gets the value of the categoryAssignmentsCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCategoryAssignmentsCount() {
        return categoryAssignmentsCount;
    }

    /**
     * Sets the value of the categoryAssignmentsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCategoryAssignmentsCount(Integer value) {
        this.categoryAssignmentsCount = value;
    }

    /**
     * Gets the value of the categoryCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCategoryCount() {
        return categoryCount;
    }

    /**
     * Sets the value of the categoryCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCategoryCount(Integer value) {
        this.categoryCount = value;
    }

    /**
     * Gets the value of the defaultCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyDTO }
     *     
     */
    public CurrencyDTO getDefaultCurrency() {
        return defaultCurrency;
    }

    /**
     * Sets the value of the defaultCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyDTO }
     *     
     */
    public void setDefaultCurrency(CurrencyDTO value) {
        this.defaultCurrency = value;
    }

    /**
     * Gets the value of the defaultCurrencyIsoCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultCurrencyIsoCode() {
        return defaultCurrencyIsoCode;
    }

    /**
     * Sets the value of the defaultCurrencyIsoCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultCurrencyIsoCode(String value) {
        this.defaultCurrencyIsoCode = value;
    }

    /**
     * Gets the value of the importAgreement property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isImportAgreement() {
        return importAgreement;
    }

    /**
     * Sets the value of the importAgreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setImportAgreement(Boolean value) {
        this.importAgreement = value;
    }

    /**
     * Gets the value of the importBuyer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isImportBuyer() {
        return importBuyer;
    }

    /**
     * Sets the value of the importBuyer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setImportBuyer(Boolean value) {
        this.importBuyer = value;
    }

    /**
     * Gets the value of the importLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageDTO }
     *     
     */
    public LanguageDTO getImportLanguage() {
        return importLanguage;
    }

    /**
     * Sets the value of the importLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageDTO }
     *     
     */
    public void setImportLanguage(LanguageDTO value) {
        this.importLanguage = value;
    }

    /**
     * Gets the value of the importLanguageIsoCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportLanguageIsoCode() {
        return importLanguageIsoCode;
    }

    /**
     * Sets the value of the importLanguageIsoCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportLanguageIsoCode(String value) {
        this.importLanguageIsoCode = value;
    }

    /**
     * Gets the value of the importSupplier property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isImportSupplier() {
        return importSupplier;
    }

    /**
     * Sets the value of the importSupplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setImportSupplier(Boolean value) {
        this.importSupplier = value;
    }

    /**
     * Gets the value of the keywordCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getKeywordCount() {
        return keywordCount;
    }

    /**
     * Sets the value of the keywordCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setKeywordCount(Integer value) {
        this.keywordCount = value;
    }

    /**
     * Gets the value of the keywordType property.
     * 
     * @return
     *     possible object is
     *     {@link ComposedTypeDTO }
     *     
     */
    public ComposedTypeDTO getKeywordType() {
        return keywordType;
    }

    /**
     * Sets the value of the keywordType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComposedTypeDTO }
     *     
     */
    public void setKeywordType(ComposedTypeDTO value) {
        this.keywordType = value;
    }

    /**
     * Gets the value of the localizationUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLocalizationUpdate() {
        return localizationUpdate;
    }

    /**
     * Sets the value of the localizationUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLocalizationUpdate(Boolean value) {
        this.localizationUpdate = value;
    }

    /**
     * Gets the value of the mediasMedia property.
     * 
     * @return
     *     possible object is
     *     {@link BmeCatJobMediaDTO }
     *     
     */
    public BmeCatJobMediaDTO getMediasMedia() {
        return mediasMedia;
    }

    /**
     * Sets the value of the mediasMedia property.
     * 
     * @param value
     *     allowed object is
     *     {@link BmeCatJobMediaDTO }
     *     
     */
    public void setMediasMedia(BmeCatJobMediaDTO value) {
        this.mediasMedia = value;
    }

    /**
     * Gets the value of the mimeCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMimeCount() {
        return mimeCount;
    }

    /**
     * Sets the value of the mimeCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMimeCount(Integer value) {
        this.mimeCount = value;
    }

    /**
     * Gets the value of the previousUpdateVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPreviousUpdateVersion() {
        return previousUpdateVersion;
    }

    /**
     * Sets the value of the previousUpdateVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPreviousUpdateVersion(Integer value) {
        this.previousUpdateVersion = value;
    }

    /**
     * Gets the value of the referenceMedias property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReferenceMedias() {
        return referenceMedias;
    }

    /**
     * Sets the value of the referenceMedias property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReferenceMedias(Boolean value) {
        this.referenceMedias = value;
    }

    /**
     * Gets the value of the territories property.
     * 
     * @return
     *     possible object is
     *     {@link BmeCatImportCronJobDTO.Territories }
     *     
     */
    public BmeCatImportCronJobDTO.Territories getTerritories() {
        return territories;
    }

    /**
     * Sets the value of the territories property.
     * 
     * @param value
     *     allowed object is
     *     {@link BmeCatImportCronJobDTO.Territories }
     *     
     */
    public void setTerritories(BmeCatImportCronJobDTO.Territories value) {
        this.territories = value;
    }

    /**
     * Gets the value of the transactionMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionMode() {
        return transactionMode;
    }

    /**
     * Sets the value of the transactionMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionMode(String value) {
        this.transactionMode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Territories {

        protected List<String> value;

        /**
         * Gets the value of the value property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the value property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getValue() {
            if (value == null) {
                value = new ArrayList<String>();
            }
            return this.value;
        }

    }

}
