//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import org.mule.api.annotations.param.RefOnly;


/**
 * <p>Java class for catalogVersionDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="catalogVersionDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}itemDTO">
 *       &lt;sequence>
 *         &lt;element name="active" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="agreements" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}agreement" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}catalog" minOccurs="0"/>
 *         &lt;element name="categorySystemDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="categorySystemID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="categorySystemName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="defaultCurrency" type="{}currencyDTO" minOccurs="0"/>
 *         &lt;element name="facetSearchConfigs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="solrFacetSearchConfig" type="{}solrFacetSearchConfigDTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="generationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="generatorInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inclAssurance" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="inclDuty" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="inclFreight" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="inclPacking" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="incomingSynchronizations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="syncItemJob" type="{}syncItemJobDTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="indexSchemas" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="hyend2IndexSchema" type="{}hyend2IndexSchemaDTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="languages" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}language" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="mimeRootDirectory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mnemonic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="previews" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="previewData" type="{}previewDataDTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="previousUpdateVersion" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="readPrincipals" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}principal" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="rootCategories" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}category" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="synchronizations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="syncItemJob" type="{}syncItemJobDTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="territories" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}country" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="writePrincipals" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}principal" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "catalogVersionDTO", propOrder = {
    "active",
    "agreements",
    "catalog",
    "categorySystemDescription",
    "categorySystemID",
    "categorySystemName",
    "defaultCurrency",
    "facetSearchConfigs",
    "generationDate",
    "generatorInfo",
    "inclAssurance",
    "inclDuty",
    "inclFreight",
    "inclPacking",
    "incomingSynchronizations",
    "indexSchemas",
    "languages",
    "mimeRootDirectory",
    "mnemonic",
    "previews",
    "previousUpdateVersion",
    "readPrincipals",
    "rootCategories",
    "synchronizations",
    "territories",
    "writePrincipals"
})
@XmlSeeAlso({
    ClassificationSystemVersionDTO.class
})
@XmlRootElement(name="catalogversion")
public class CatalogVersionDTO
    extends ItemDTO
{

    protected Boolean active;
    protected CatalogVersionDTO.Agreements agreements;
    @RefOnly
    protected CatalogDTO catalog;
    protected String categorySystemDescription;
    protected String categorySystemID;
    protected String categorySystemName;
    protected CurrencyDTO defaultCurrency;
    protected CatalogVersionDTO.FacetSearchConfigs facetSearchConfigs;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar generationDate;
    protected String generatorInfo;
    protected Boolean inclAssurance;
    protected Boolean inclDuty;
    protected Boolean inclFreight;
    protected Boolean inclPacking;
    protected CatalogVersionDTO.IncomingSynchronizations incomingSynchronizations;
    protected CatalogVersionDTO.IndexSchemas indexSchemas;
    protected CatalogVersionDTO.Languages languages;
    protected String mimeRootDirectory;
    protected String mnemonic;
    protected CatalogVersionDTO.Previews previews;
    protected Integer previousUpdateVersion;
    protected CatalogVersionDTO.ReadPrincipals readPrincipals;
    protected CatalogVersionDTO.RootCategories rootCategories;
    protected CatalogVersionDTO.Synchronizations synchronizations;
    protected CatalogVersionDTO.Territories territories;
    protected CatalogVersionDTO.WritePrincipals writePrincipals;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the active property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setActive(Boolean value) {
        this.active = value;
    }

    /**
     * Gets the value of the agreements property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogVersionDTO.Agreements }
     *     
     */
    public CatalogVersionDTO.Agreements getAgreements() {
        return agreements;
    }

    /**
     * Sets the value of the agreements property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogVersionDTO.Agreements }
     *     
     */
    public void setAgreements(CatalogVersionDTO.Agreements value) {
        this.agreements = value;
    }

    /**
     * Gets the value of the catalog property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogDTO }
     *     
     */
    public CatalogDTO getCatalog() {
        return catalog;
    }

    /**
     * Sets the value of the catalog property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogDTO }
     *     
     */
    public void setCatalog(CatalogDTO value) {
        this.catalog = value;
    }

    /**
     * Gets the value of the categorySystemDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategorySystemDescription() {
        return categorySystemDescription;
    }

    /**
     * Sets the value of the categorySystemDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategorySystemDescription(String value) {
        this.categorySystemDescription = value;
    }

    /**
     * Gets the value of the categorySystemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategorySystemID() {
        return categorySystemID;
    }

    /**
     * Sets the value of the categorySystemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategorySystemID(String value) {
        this.categorySystemID = value;
    }

    /**
     * Gets the value of the categorySystemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategorySystemName() {
        return categorySystemName;
    }

    /**
     * Sets the value of the categorySystemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategorySystemName(String value) {
        this.categorySystemName = value;
    }

    /**
     * Gets the value of the defaultCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyDTO }
     *     
     */
    public CurrencyDTO getDefaultCurrency() {
        return defaultCurrency;
    }

    /**
     * Sets the value of the defaultCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyDTO }
     *     
     */
    public void setDefaultCurrency(CurrencyDTO value) {
        this.defaultCurrency = value;
    }

    /**
     * Gets the value of the facetSearchConfigs property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogVersionDTO.FacetSearchConfigs }
     *     
     */
    public CatalogVersionDTO.FacetSearchConfigs getFacetSearchConfigs() {
        return facetSearchConfigs;
    }

    /**
     * Sets the value of the facetSearchConfigs property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogVersionDTO.FacetSearchConfigs }
     *     
     */
    public void setFacetSearchConfigs(CatalogVersionDTO.FacetSearchConfigs value) {
        this.facetSearchConfigs = value;
    }

    /**
     * Gets the value of the generationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGenerationDate() {
        return generationDate;
    }

    /**
     * Sets the value of the generationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGenerationDate(XMLGregorianCalendar value) {
        this.generationDate = value;
    }

    /**
     * Gets the value of the generatorInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneratorInfo() {
        return generatorInfo;
    }

    /**
     * Sets the value of the generatorInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneratorInfo(String value) {
        this.generatorInfo = value;
    }

    /**
     * Gets the value of the inclAssurance property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInclAssurance() {
        return inclAssurance;
    }

    /**
     * Sets the value of the inclAssurance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInclAssurance(Boolean value) {
        this.inclAssurance = value;
    }

    /**
     * Gets the value of the inclDuty property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInclDuty() {
        return inclDuty;
    }

    /**
     * Sets the value of the inclDuty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInclDuty(Boolean value) {
        this.inclDuty = value;
    }

    /**
     * Gets the value of the inclFreight property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInclFreight() {
        return inclFreight;
    }

    /**
     * Sets the value of the inclFreight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInclFreight(Boolean value) {
        this.inclFreight = value;
    }

    /**
     * Gets the value of the inclPacking property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInclPacking() {
        return inclPacking;
    }

    /**
     * Sets the value of the inclPacking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInclPacking(Boolean value) {
        this.inclPacking = value;
    }

    /**
     * Gets the value of the incomingSynchronizations property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogVersionDTO.IncomingSynchronizations }
     *     
     */
    public CatalogVersionDTO.IncomingSynchronizations getIncomingSynchronizations() {
        return incomingSynchronizations;
    }

    /**
     * Sets the value of the incomingSynchronizations property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogVersionDTO.IncomingSynchronizations }
     *     
     */
    public void setIncomingSynchronizations(CatalogVersionDTO.IncomingSynchronizations value) {
        this.incomingSynchronizations = value;
    }

    /**
     * Gets the value of the indexSchemas property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogVersionDTO.IndexSchemas }
     *     
     */
    public CatalogVersionDTO.IndexSchemas getIndexSchemas() {
        return indexSchemas;
    }

    /**
     * Sets the value of the indexSchemas property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogVersionDTO.IndexSchemas }
     *     
     */
    public void setIndexSchemas(CatalogVersionDTO.IndexSchemas value) {
        this.indexSchemas = value;
    }

    /**
     * Gets the value of the languages property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogVersionDTO.Languages }
     *     
     */
    public CatalogVersionDTO.Languages getLanguages() {
        return languages;
    }

    /**
     * Sets the value of the languages property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogVersionDTO.Languages }
     *     
     */
    public void setLanguages(CatalogVersionDTO.Languages value) {
        this.languages = value;
    }

    /**
     * Gets the value of the mimeRootDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMimeRootDirectory() {
        return mimeRootDirectory;
    }

    /**
     * Sets the value of the mimeRootDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMimeRootDirectory(String value) {
        this.mimeRootDirectory = value;
    }

    /**
     * Gets the value of the mnemonic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMnemonic() {
        return mnemonic;
    }

    /**
     * Sets the value of the mnemonic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMnemonic(String value) {
        this.mnemonic = value;
    }

    /**
     * Gets the value of the previews property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogVersionDTO.Previews }
     *     
     */
    public CatalogVersionDTO.Previews getPreviews() {
        return previews;
    }

    /**
     * Sets the value of the previews property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogVersionDTO.Previews }
     *     
     */
    public void setPreviews(CatalogVersionDTO.Previews value) {
        this.previews = value;
    }

    /**
     * Gets the value of the previousUpdateVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPreviousUpdateVersion() {
        return previousUpdateVersion;
    }

    /**
     * Sets the value of the previousUpdateVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPreviousUpdateVersion(Integer value) {
        this.previousUpdateVersion = value;
    }

    /**
     * Gets the value of the readPrincipals property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogVersionDTO.ReadPrincipals }
     *     
     */
    public CatalogVersionDTO.ReadPrincipals getReadPrincipals() {
        return readPrincipals;
    }

    /**
     * Sets the value of the readPrincipals property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogVersionDTO.ReadPrincipals }
     *     
     */
    public void setReadPrincipals(CatalogVersionDTO.ReadPrincipals value) {
        this.readPrincipals = value;
    }

    /**
     * Gets the value of the rootCategories property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogVersionDTO.RootCategories }
     *     
     */
    public CatalogVersionDTO.RootCategories getRootCategories() {
        return rootCategories;
    }

    /**
     * Sets the value of the rootCategories property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogVersionDTO.RootCategories }
     *     
     */
    public void setRootCategories(CatalogVersionDTO.RootCategories value) {
        this.rootCategories = value;
    }

    /**
     * Gets the value of the synchronizations property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogVersionDTO.Synchronizations }
     *     
     */
    public CatalogVersionDTO.Synchronizations getSynchronizations() {
        return synchronizations;
    }

    /**
     * Sets the value of the synchronizations property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogVersionDTO.Synchronizations }
     *     
     */
    public void setSynchronizations(CatalogVersionDTO.Synchronizations value) {
        this.synchronizations = value;
    }

    /**
     * Gets the value of the territories property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogVersionDTO.Territories }
     *     
     */
    public CatalogVersionDTO.Territories getTerritories() {
        return territories;
    }

    /**
     * Sets the value of the territories property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogVersionDTO.Territories }
     *     
     */
    public void setTerritories(CatalogVersionDTO.Territories value) {
        this.territories = value;
    }

    /**
     * Gets the value of the writePrincipals property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogVersionDTO.WritePrincipals }
     *     
     */
    public CatalogVersionDTO.WritePrincipals getWritePrincipals() {
        return writePrincipals;
    }

    /**
     * Sets the value of the writePrincipals property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogVersionDTO.WritePrincipals }
     *     
     */
    public void setWritePrincipals(CatalogVersionDTO.WritePrincipals value) {
        this.writePrincipals = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}agreement" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "agreement"
    })
    public static class Agreements {

        protected List<AgreementDTO> agreement;

        /**
         * Gets the value of the agreement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the agreement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAgreement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AgreementDTO }
         * 
         * 
         */
        public List<AgreementDTO> getAgreement() {
            if (agreement == null) {
                agreement = new ArrayList<AgreementDTO>();
            }
            return this.agreement;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="solrFacetSearchConfig" type="{}solrFacetSearchConfigDTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "solrFacetSearchConfig"
    })
    public static class FacetSearchConfigs {

        protected List<SolrFacetSearchConfigDTO> solrFacetSearchConfig;

        /**
         * Gets the value of the solrFacetSearchConfig property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the solrFacetSearchConfig property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSolrFacetSearchConfig().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SolrFacetSearchConfigDTO }
         * 
         * 
         */
        public List<SolrFacetSearchConfigDTO> getSolrFacetSearchConfig() {
            if (solrFacetSearchConfig == null) {
                solrFacetSearchConfig = new ArrayList<SolrFacetSearchConfigDTO>();
            }
            return this.solrFacetSearchConfig;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="syncItemJob" type="{}syncItemJobDTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "syncItemJob"
    })
    public static class IncomingSynchronizations {

        protected List<SyncItemJobDTO> syncItemJob;

        /**
         * Gets the value of the syncItemJob property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the syncItemJob property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSyncItemJob().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SyncItemJobDTO }
         * 
         * 
         */
        public List<SyncItemJobDTO> getSyncItemJob() {
            if (syncItemJob == null) {
                syncItemJob = new ArrayList<SyncItemJobDTO>();
            }
            return this.syncItemJob;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="hyend2IndexSchema" type="{}hyend2IndexSchemaDTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hyend2IndexSchema"
    })
    public static class IndexSchemas {

        protected List<Hyend2IndexSchemaDTO> hyend2IndexSchema;

        /**
         * Gets the value of the hyend2IndexSchema property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the hyend2IndexSchema property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHyend2IndexSchema().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Hyend2IndexSchemaDTO }
         * 
         * 
         */
        public List<Hyend2IndexSchemaDTO> getHyend2IndexSchema() {
            if (hyend2IndexSchema == null) {
                hyend2IndexSchema = new ArrayList<Hyend2IndexSchemaDTO>();
            }
            return this.hyend2IndexSchema;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}language" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "language"
    })
    public static class Languages {

        protected List<LanguageDTO> language;

        /**
         * Gets the value of the language property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the language property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLanguage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LanguageDTO }
         * 
         * 
         */
        public List<LanguageDTO> getLanguage() {
            if (language == null) {
                language = new ArrayList<LanguageDTO>();
            }
            return this.language;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="previewData" type="{}previewDataDTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "previewData"
    })
    public static class Previews {

        protected List<PreviewDataDTO> previewData;

        /**
         * Gets the value of the previewData property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the previewData property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPreviewData().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PreviewDataDTO }
         * 
         * 
         */
        public List<PreviewDataDTO> getPreviewData() {
            if (previewData == null) {
                previewData = new ArrayList<PreviewDataDTO>();
            }
            return this.previewData;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}principal" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "principal"
    })
    public static class ReadPrincipals {

        protected List<PrincipalDTO> principal;

        /**
         * Gets the value of the principal property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the principal property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPrincipal().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PrincipalDTO }
         * 
         * 
         */
        public List<PrincipalDTO> getPrincipal() {
            if (principal == null) {
                principal = new ArrayList<PrincipalDTO>();
            }
            return this.principal;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}category" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "category"
    })
    public static class RootCategories {

        protected List<CategoryDTO> category;

        /**
         * Gets the value of the category property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the category property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCategory().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CategoryDTO }
         * 
         * 
         */
        public List<CategoryDTO> getCategory() {
            if (category == null) {
                category = new ArrayList<CategoryDTO>();
            }
            return this.category;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="syncItemJob" type="{}syncItemJobDTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "syncItemJob"
    })
    public static class Synchronizations {

        protected List<SyncItemJobDTO> syncItemJob;

        /**
         * Gets the value of the syncItemJob property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the syncItemJob property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSyncItemJob().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SyncItemJobDTO }
         * 
         * 
         */
        public List<SyncItemJobDTO> getSyncItemJob() {
            if (syncItemJob == null) {
                syncItemJob = new ArrayList<SyncItemJobDTO>();
            }
            return this.syncItemJob;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}country" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "country"
    })
    public static class Territories {

        protected List<CountryDTO> country;

        /**
         * Gets the value of the country property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the country property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCountry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CountryDTO }
         * 
         * 
         */
        public List<CountryDTO> getCountry() {
            if (country == null) {
                country = new ArrayList<CountryDTO>();
            }
            return this.country;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}principal" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "principal"
    })
    public static class WritePrincipals {

        protected List<PrincipalDTO> principal;

        /**
         * Gets the value of the principal property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the principal property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPrincipal().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PrincipalDTO }
         * 
         * 
         */
        public List<PrincipalDTO> getPrincipal() {
            if (principal == null) {
                principal = new ArrayList<PrincipalDTO>();
            }
            return this.principal;
        }

    }

}
