//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for chapterConfigurationDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="chapterConfigurationDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}itemDTO">
 *       &lt;sequence>
 *         &lt;element name="chapterLevel" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="chapterParagraphStyle" type="{}chapterParagraphStyleDTO" minOccurs="0"/>
 *         &lt;element name="chaptersConfiguration" type="{}chaptersConfigurationDTO" minOccurs="0"/>
 *         &lt;element name="flowControl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="showChapter" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "chapterConfigurationDTO", propOrder = {
    "chapterLevel",
    "chapterParagraphStyle",
    "chaptersConfiguration",
    "flowControl",
    "showChapter"
})
public class ChapterConfigurationDTO
    extends ItemDTO
{

    protected Integer chapterLevel;
    protected ChapterParagraphStyleDTO chapterParagraphStyle;
    protected ChaptersConfigurationDTO chaptersConfiguration;
    protected String flowControl;
    protected Boolean showChapter;

    /**
     * Gets the value of the chapterLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getChapterLevel() {
        return chapterLevel;
    }

    /**
     * Sets the value of the chapterLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setChapterLevel(Integer value) {
        this.chapterLevel = value;
    }

    /**
     * Gets the value of the chapterParagraphStyle property.
     * 
     * @return
     *     possible object is
     *     {@link ChapterParagraphStyleDTO }
     *     
     */
    public ChapterParagraphStyleDTO getChapterParagraphStyle() {
        return chapterParagraphStyle;
    }

    /**
     * Sets the value of the chapterParagraphStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChapterParagraphStyleDTO }
     *     
     */
    public void setChapterParagraphStyle(ChapterParagraphStyleDTO value) {
        this.chapterParagraphStyle = value;
    }

    /**
     * Gets the value of the chaptersConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link ChaptersConfigurationDTO }
     *     
     */
    public ChaptersConfigurationDTO getChaptersConfiguration() {
        return chaptersConfiguration;
    }

    /**
     * Sets the value of the chaptersConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChaptersConfigurationDTO }
     *     
     */
    public void setChaptersConfiguration(ChaptersConfigurationDTO value) {
        this.chaptersConfiguration = value;
    }

    /**
     * Gets the value of the flowControl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlowControl() {
        return flowControl;
    }

    /**
     * Sets the value of the flowControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlowControl(String value) {
        this.flowControl = value;
    }

    /**
     * Gets the value of the showChapter property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowChapter() {
        return showChapter;
    }

    /**
     * Sets the value of the showChapter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowChapter(Boolean value) {
        this.showChapter = value;
    }

}
