//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cmsLinkComponentDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cmsLinkComponentDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}simpleCMSComponentDTO">
 *       &lt;sequence>
 *         &lt;element ref="{}category" minOccurs="0"/>
 *         &lt;element name="categoryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contentPage" type="{}contentPageDTO" minOccurs="0"/>
 *         &lt;element name="contentPageLabelOrId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="external" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="linkName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="navigationNodes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cMSNavigationNode" type="{}cmsNavigationNodeDTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}product" minOccurs="0"/>
 *         &lt;element name="productCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="styleAttributes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="target" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cmsLinkComponentDTO", propOrder = {
    "category",
    "categoryCode",
    "contentPage",
    "contentPageLabelOrId",
    "external",
    "linkName",
    "navigationNodes",
    "product",
    "productCode",
    "styleAttributes",
    "target",
    "url"
})
public class CmsLinkComponentDTO
    extends SimpleCMSComponentDTO
{

    protected CategoryDTO category;
    protected String categoryCode;
    protected ContentPageDTO contentPage;
    protected String contentPageLabelOrId;
    protected boolean external;
    protected String linkName;
    protected CmsLinkComponentDTO.NavigationNodes navigationNodes;
    protected ProductDTO product;
    protected String productCode;
    protected String styleAttributes;
    protected String target;
    protected String url;

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link CategoryDTO }
     *     
     */
    public CategoryDTO getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoryDTO }
     *     
     */
    public void setCategory(CategoryDTO value) {
        this.category = value;
    }

    /**
     * Gets the value of the categoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryCode() {
        return categoryCode;
    }

    /**
     * Sets the value of the categoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryCode(String value) {
        this.categoryCode = value;
    }

    /**
     * Gets the value of the contentPage property.
     * 
     * @return
     *     possible object is
     *     {@link ContentPageDTO }
     *     
     */
    public ContentPageDTO getContentPage() {
        return contentPage;
    }

    /**
     * Sets the value of the contentPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentPageDTO }
     *     
     */
    public void setContentPage(ContentPageDTO value) {
        this.contentPage = value;
    }

    /**
     * Gets the value of the contentPageLabelOrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentPageLabelOrId() {
        return contentPageLabelOrId;
    }

    /**
     * Sets the value of the contentPageLabelOrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentPageLabelOrId(String value) {
        this.contentPageLabelOrId = value;
    }

    /**
     * Gets the value of the external property.
     * 
     */
    public boolean isExternal() {
        return external;
    }

    /**
     * Sets the value of the external property.
     * 
     */
    public void setExternal(boolean value) {
        this.external = value;
    }

    /**
     * Gets the value of the linkName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkName() {
        return linkName;
    }

    /**
     * Sets the value of the linkName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkName(String value) {
        this.linkName = value;
    }

    /**
     * Gets the value of the navigationNodes property.
     * 
     * @return
     *     possible object is
     *     {@link CmsLinkComponentDTO.NavigationNodes }
     *     
     */
    public CmsLinkComponentDTO.NavigationNodes getNavigationNodes() {
        return navigationNodes;
    }

    /**
     * Sets the value of the navigationNodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CmsLinkComponentDTO.NavigationNodes }
     *     
     */
    public void setNavigationNodes(CmsLinkComponentDTO.NavigationNodes value) {
        this.navigationNodes = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link ProductDTO }
     *     
     */
    public ProductDTO getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductDTO }
     *     
     */
    public void setProduct(ProductDTO value) {
        this.product = value;
    }

    /**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(String value) {
        this.productCode = value;
    }

    /**
     * Gets the value of the styleAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyleAttributes() {
        return styleAttributes;
    }

    /**
     * Sets the value of the styleAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyleAttributes(String value) {
        this.styleAttributes = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarget(String value) {
        this.target = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="cMSNavigationNode" type="{}cmsNavigationNodeDTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cmsNavigationNode"
    })
    public static class NavigationNodes {

        @XmlElement(name = "cMSNavigationNode")
        protected List<CmsNavigationNodeDTO> cmsNavigationNode;

        /**
         * Gets the value of the cmsNavigationNode property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cmsNavigationNode property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCMSNavigationNode().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CmsNavigationNodeDTO }
         * 
         * 
         */
        public List<CmsNavigationNodeDTO> getCMSNavigationNode() {
            if (cmsNavigationNode == null) {
                cmsNavigationNode = new ArrayList<CmsNavigationNodeDTO>();
            }
            return this.cmsNavigationNode;
        }

    }

}
