//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cometFileDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cometFileDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}mediaDTO">
 *       &lt;sequence>
 *         &lt;element name="chapterPreview" type="{}chapterDTO" minOccurs="0"/>
 *         &lt;element name="configuration" type="{}cometConfigurationDTO" minOccurs="0"/>
 *         &lt;element name="pagePreview" type="{}pageDTO" minOccurs="0"/>
 *         &lt;element name="publicationPreview" type="{}publicationDTO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cometFileDTO", propOrder = {
    "chapterPreview",
    "configuration",
    "pagePreview",
    "publicationPreview"
})
public class CometFileDTO
    extends MediaDTO
{

    protected ChapterDTO chapterPreview;
    protected CometConfigurationDTO configuration;
    protected PageDTO pagePreview;
    protected PublicationDTO publicationPreview;

    /**
     * Gets the value of the chapterPreview property.
     * 
     * @return
     *     possible object is
     *     {@link ChapterDTO }
     *     
     */
    public ChapterDTO getChapterPreview() {
        return chapterPreview;
    }

    /**
     * Sets the value of the chapterPreview property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChapterDTO }
     *     
     */
    public void setChapterPreview(ChapterDTO value) {
        this.chapterPreview = value;
    }

    /**
     * Gets the value of the configuration property.
     * 
     * @return
     *     possible object is
     *     {@link CometConfigurationDTO }
     *     
     */
    public CometConfigurationDTO getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link CometConfigurationDTO }
     *     
     */
    public void setConfiguration(CometConfigurationDTO value) {
        this.configuration = value;
    }

    /**
     * Gets the value of the pagePreview property.
     * 
     * @return
     *     possible object is
     *     {@link PageDTO }
     *     
     */
    public PageDTO getPagePreview() {
        return pagePreview;
    }

    /**
     * Sets the value of the pagePreview property.
     * 
     * @param value
     *     allowed object is
     *     {@link PageDTO }
     *     
     */
    public void setPagePreview(PageDTO value) {
        this.pagePreview = value;
    }

    /**
     * Gets the value of the publicationPreview property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationDTO }
     *     
     */
    public PublicationDTO getPublicationPreview() {
        return publicationPreview;
    }

    /**
     * Sets the value of the publicationPreview property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationDTO }
     *     
     */
    public void setPublicationPreview(PublicationDTO value) {
        this.publicationPreview = value;
    }

}
