//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for compositeCronJobDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="compositeCronJobDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}cronJobDTO">
 *       &lt;sequence>
 *         &lt;element name="compositeEntries" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="compositeEntry" type="{}compositeEntryDTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "compositeCronJobDTO", propOrder = {
    "compositeEntries"
})
public class CompositeCronJobDTO
    extends CronJobDTO
{

    protected CompositeCronJobDTO.CompositeEntries compositeEntries;

    /**
     * Gets the value of the compositeEntries property.
     * 
     * @return
     *     possible object is
     *     {@link CompositeCronJobDTO.CompositeEntries }
     *     
     */
    public CompositeCronJobDTO.CompositeEntries getCompositeEntries() {
        return compositeEntries;
    }

    /**
     * Sets the value of the compositeEntries property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompositeCronJobDTO.CompositeEntries }
     *     
     */
    public void setCompositeEntries(CompositeCronJobDTO.CompositeEntries value) {
        this.compositeEntries = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="compositeEntry" type="{}compositeEntryDTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "compositeEntry"
    })
    public static class CompositeEntries {

        protected List<CompositeEntryDTO> compositeEntry;

        /**
         * Gets the value of the compositeEntry property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the compositeEntry property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCompositeEntry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CompositeEntryDTO }
         * 
         * 
         */
        public List<CompositeEntryDTO> getCompositeEntry() {
            if (compositeEntry == null) {
                compositeEntry = new ArrayList<CompositeEntryDTO>();
            }
            return this.compositeEntry;
        }

    }

}
