//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cronJobDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cronJobDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}itemDTO">
 *       &lt;sequence>
 *         &lt;element name="active" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="changeRecordingEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="emailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="errorMode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}job" minOccurs="0"/>
 *         &lt;element name="logLevelDatabase" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="logLevelFile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="logText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="logToDatabase" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="logToFile" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="nodeID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="removeOnExit" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="requestAbort" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="requestAbortStep" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sessionCurrency" type="{}currencyDTO" minOccurs="0"/>
 *         &lt;element name="sessionLanguage" type="{}languageDTO" minOccurs="0"/>
 *         &lt;element name="sessionUser" type="{}userDTO" minOccurs="0"/>
 *         &lt;element name="singleExecutable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="timeTable" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cronJobDTO", propOrder = {
    "active",
    "changeRecordingEnabled",
    "emailAddress",
    "errorMode",
    "job",
    "logLevelDatabase",
    "logLevelFile",
    "logText",
    "logToDatabase",
    "logToFile",
    "nodeID",
    "priority",
    "removeOnExit",
    "requestAbort",
    "requestAbortStep",
    "result",
    "sessionCurrency",
    "sessionLanguage",
    "sessionUser",
    "singleExecutable",
    "status",
    "timeTable"
})
@XmlSeeAlso({
    ImpExExportCronJobDTO.class,
    CartRemovalCronJobDTO.class,
    SyncItemCronJobDTO.class,
    SolrIndexOptimizationCronJobDTO.class,
    MoveMediaCronJobDTO.class,
    SolrIndexerCronJobDTO.class,
    MobileSendMessageCronJobDTO.class,
    UncollectedOrdersCronJobDTO.class,
    CompareCatalogVersionsCronJobDTO.class,
    Hyend2ExportCronJobDTO.class,
    MediaFolderStructureMigrationCronJobDTO.class,
    OrderScheduleCronJobDTO.class,
    GeocodeAddressesCronJobDTO.class,
    CleanUpCronJobDTO.class,
    CelumSynchronizationCronJobDTO.class,
    CompositeCronJobDTO.class,
    RemoveCatalogVersionCronJobDTO.class,
    WorkflowDTO.class,
    SolrUpdateSynonymsCronJobDTO.class,
    SolrUpdateStopWordsCronJobDTO.class,
    CelumPicturesIntegrationCronJobBaseDTO.class,
    SolrQueryStatisticsCollectorCronJobDTO.class,
    SessionTimeoutCronJobDTO.class,
    RemoveItemsCronJobDTO.class,
    RemoveOrphanedFilesCronJobDTO.class,
    CartToOrderCronJobDTO.class,
    OrganizationOrdersReportingCronJobDTO.class,
    ExportDataCronJobDTO.class,
    OrderTemplateToOrderCronJobDTO.class,
    MultipleCatalogsSyncCronJobDTO.class,
    MediaProcessCronJobDTO.class,
    ImpExImportCronJobDTO.class
})
public class CronJobDTO
    extends ItemDTO
{

    protected Boolean active;
    protected Boolean changeRecordingEnabled;
    protected String emailAddress;
    protected String errorMode;
    protected JobDTO job;
    protected String logLevelDatabase;
    protected String logLevelFile;
    protected String logText;
    protected Boolean logToDatabase;
    protected Boolean logToFile;
    protected Integer nodeID;
    protected Integer priority;
    protected Boolean removeOnExit;
    protected Boolean requestAbort;
    protected Boolean requestAbortStep;
    protected String result;
    protected CurrencyDTO sessionCurrency;
    protected LanguageDTO sessionLanguage;
    protected UserDTO sessionUser;
    protected Boolean singleExecutable;
    protected String status;
    protected String timeTable;
    @XmlAttribute(name = "code")
    protected String code;

    /**
     * Gets the value of the active property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setActive(Boolean value) {
        this.active = value;
    }

    /**
     * Gets the value of the changeRecordingEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isChangeRecordingEnabled() {
        return changeRecordingEnabled;
    }

    /**
     * Sets the value of the changeRecordingEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setChangeRecordingEnabled(Boolean value) {
        this.changeRecordingEnabled = value;
    }

    /**
     * Gets the value of the emailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress(String value) {
        this.emailAddress = value;
    }

    /**
     * Gets the value of the errorMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMode() {
        return errorMode;
    }

    /**
     * Sets the value of the errorMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMode(String value) {
        this.errorMode = value;
    }

    /**
     * Gets the value of the job property.
     * 
     * @return
     *     possible object is
     *     {@link JobDTO }
     *     
     */
    public JobDTO getJob() {
        return job;
    }

    /**
     * Sets the value of the job property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobDTO }
     *     
     */
    public void setJob(JobDTO value) {
        this.job = value;
    }

    /**
     * Gets the value of the logLevelDatabase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogLevelDatabase() {
        return logLevelDatabase;
    }

    /**
     * Sets the value of the logLevelDatabase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogLevelDatabase(String value) {
        this.logLevelDatabase = value;
    }

    /**
     * Gets the value of the logLevelFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogLevelFile() {
        return logLevelFile;
    }

    /**
     * Sets the value of the logLevelFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogLevelFile(String value) {
        this.logLevelFile = value;
    }

    /**
     * Gets the value of the logText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogText() {
        return logText;
    }

    /**
     * Sets the value of the logText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogText(String value) {
        this.logText = value;
    }

    /**
     * Gets the value of the logToDatabase property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLogToDatabase() {
        return logToDatabase;
    }

    /**
     * Sets the value of the logToDatabase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLogToDatabase(Boolean value) {
        this.logToDatabase = value;
    }

    /**
     * Gets the value of the logToFile property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLogToFile() {
        return logToFile;
    }

    /**
     * Sets the value of the logToFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLogToFile(Boolean value) {
        this.logToFile = value;
    }

    /**
     * Gets the value of the nodeID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNodeID() {
        return nodeID;
    }

    /**
     * Sets the value of the nodeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNodeID(Integer value) {
        this.nodeID = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPriority(Integer value) {
        this.priority = value;
    }

    /**
     * Gets the value of the removeOnExit property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRemoveOnExit() {
        return removeOnExit;
    }

    /**
     * Sets the value of the removeOnExit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRemoveOnExit(Boolean value) {
        this.removeOnExit = value;
    }

    /**
     * Gets the value of the requestAbort property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequestAbort() {
        return requestAbort;
    }

    /**
     * Sets the value of the requestAbort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequestAbort(Boolean value) {
        this.requestAbort = value;
    }

    /**
     * Gets the value of the requestAbortStep property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequestAbortStep() {
        return requestAbortStep;
    }

    /**
     * Sets the value of the requestAbortStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequestAbortStep(Boolean value) {
        this.requestAbortStep = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResult(String value) {
        this.result = value;
    }

    /**
     * Gets the value of the sessionCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyDTO }
     *     
     */
    public CurrencyDTO getSessionCurrency() {
        return sessionCurrency;
    }

    /**
     * Sets the value of the sessionCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyDTO }
     *     
     */
    public void setSessionCurrency(CurrencyDTO value) {
        this.sessionCurrency = value;
    }

    /**
     * Gets the value of the sessionLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageDTO }
     *     
     */
    public LanguageDTO getSessionLanguage() {
        return sessionLanguage;
    }

    /**
     * Sets the value of the sessionLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageDTO }
     *     
     */
    public void setSessionLanguage(LanguageDTO value) {
        this.sessionLanguage = value;
    }

    /**
     * Gets the value of the sessionUser property.
     * 
     * @return
     *     possible object is
     *     {@link UserDTO }
     *     
     */
    public UserDTO getSessionUser() {
        return sessionUser;
    }

    /**
     * Sets the value of the sessionUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDTO }
     *     
     */
    public void setSessionUser(UserDTO value) {
        this.sessionUser = value;
    }

    /**
     * Gets the value of the singleExecutable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSingleExecutable() {
        return singleExecutable;
    }

    /**
     * Sets the value of the singleExecutable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSingleExecutable(Boolean value) {
        this.singleExecutable = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the timeTable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeTable() {
        return timeTable;
    }

    /**
     * Sets the value of the timeTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeTable(String value) {
        this.timeTable = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

}
