//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for customerDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="customerDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}userDTO">
 *       &lt;sequence>
 *         &lt;element name="contactEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="defaultPaymentInfo" type="{}paymentInfoDTO" minOccurs="0"/>
 *         &lt;element name="originalUid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="previewCatalogVersions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="catalogVersion" type="{}catalogVersionDTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}title" minOccurs="0"/>
 *         &lt;element name="token" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "customerDTO", propOrder = {
    "contactEmail",
    "customerID",
    "defaultPaymentInfo",
    "originalUid",
    "previewCatalogVersions",
    "title",
    "token",
    "type"
})
@XmlSeeAlso({
    B2BCustomerDTO.class
})
public class CustomerDTO
    extends UserDTO
{

    protected String contactEmail;
    protected String customerID;
    protected PaymentInfoDTO defaultPaymentInfo;
    protected String originalUid;
    protected CustomerDTO.PreviewCatalogVersions previewCatalogVersions;
    protected TitleDTO title;
    protected String token;
    protected String type;

    /**
     * Gets the value of the contactEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactEmail() {
        return contactEmail;
    }

    /**
     * Sets the value of the contactEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactEmail(String value) {
        this.contactEmail = value;
    }

    /**
     * Gets the value of the customerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerID() {
        return customerID;
    }

    /**
     * Sets the value of the customerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerID(String value) {
        this.customerID = value;
    }

    /**
     * Gets the value of the defaultPaymentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentInfoDTO }
     *     
     */
    public PaymentInfoDTO getDefaultPaymentInfo() {
        return defaultPaymentInfo;
    }

    /**
     * Sets the value of the defaultPaymentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentInfoDTO }
     *     
     */
    public void setDefaultPaymentInfo(PaymentInfoDTO value) {
        this.defaultPaymentInfo = value;
    }

    /**
     * Gets the value of the originalUid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalUid() {
        return originalUid;
    }

    /**
     * Sets the value of the originalUid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalUid(String value) {
        this.originalUid = value;
    }

    /**
     * Gets the value of the previewCatalogVersions property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerDTO.PreviewCatalogVersions }
     *     
     */
    public CustomerDTO.PreviewCatalogVersions getPreviewCatalogVersions() {
        return previewCatalogVersions;
    }

    /**
     * Sets the value of the previewCatalogVersions property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerDTO.PreviewCatalogVersions }
     *     
     */
    public void setPreviewCatalogVersions(CustomerDTO.PreviewCatalogVersions value) {
        this.previewCatalogVersions = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link TitleDTO }
     *     
     */
    public TitleDTO getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link TitleDTO }
     *     
     */
    public void setTitle(TitleDTO value) {
        this.title = value;
    }

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="catalogVersion" type="{}catalogVersionDTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "catalogVersion"
    })
    public static class PreviewCatalogVersions {

        protected List<CatalogVersionDTO> catalogVersion;

        /**
         * Gets the value of the catalogVersion property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the catalogVersion property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCatalogVersion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CatalogVersionDTO }
         * 
         * 
         */
        public List<CatalogVersionDTO> getCatalogVersion() {
            if (catalogVersion == null) {
                catalogVersion = new ArrayList<CatalogVersionDTO>();
            }
            return this.catalogVersion;
        }

    }

}
