//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for documentDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="documentDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}mediaDTO">
 *       &lt;sequence>
 *         &lt;element ref="{}format" minOccurs="0"/>
 *         &lt;element name="itemTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="sourceItem" type="{}itemDTO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "documentDTO", propOrder = {
    "format",
    "itemTimestamp",
    "sourceItem"
})
public class DocumentDTO
    extends MediaDTO
{

    protected FormatDTO format;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar itemTimestamp;
    protected ItemDTO sourceItem;

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link FormatDTO }
     *     
     */
    public FormatDTO getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormatDTO }
     *     
     */
    public void setFormat(FormatDTO value) {
        this.format = value;
    }

    /**
     * Gets the value of the itemTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getItemTimestamp() {
        return itemTimestamp;
    }

    /**
     * Sets the value of the itemTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setItemTimestamp(XMLGregorianCalendar value) {
        this.itemTimestamp = value;
    }

    /**
     * Gets the value of the sourceItem property.
     * 
     * @return
     *     possible object is
     *     {@link ItemDTO }
     *     
     */
    public ItemDTO getSourceItem() {
        return sourceItem;
    }

    /**
     * Sets the value of the sourceItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemDTO }
     *     
     */
    public void setSourceItem(ItemDTO value) {
        this.sourceItem = value;
    }

}
