//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for footerComponentDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="footerComponentDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}simpleCMSComponentDTO">
 *       &lt;sequence>
 *         &lt;element name="navigationNodes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cMSNavigationNode" type="{}cmsNavigationNodeDTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="notice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="wrapAfter" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "footerComponentDTO", propOrder = {
    "navigationNodes",
    "notice",
    "wrapAfter"
})
public class FooterComponentDTO
    extends SimpleCMSComponentDTO
{

    protected FooterComponentDTO.NavigationNodes navigationNodes;
    protected String notice;
    protected Integer wrapAfter;

    /**
     * Gets the value of the navigationNodes property.
     * 
     * @return
     *     possible object is
     *     {@link FooterComponentDTO.NavigationNodes }
     *     
     */
    public FooterComponentDTO.NavigationNodes getNavigationNodes() {
        return navigationNodes;
    }

    /**
     * Sets the value of the navigationNodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link FooterComponentDTO.NavigationNodes }
     *     
     */
    public void setNavigationNodes(FooterComponentDTO.NavigationNodes value) {
        this.navigationNodes = value;
    }

    /**
     * Gets the value of the notice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotice() {
        return notice;
    }

    /**
     * Sets the value of the notice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotice(String value) {
        this.notice = value;
    }

    /**
     * Gets the value of the wrapAfter property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWrapAfter() {
        return wrapAfter;
    }

    /**
     * Sets the value of the wrapAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWrapAfter(Integer value) {
        this.wrapAfter = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="cMSNavigationNode" type="{}cmsNavigationNodeDTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cmsNavigationNode"
    })
    public static class NavigationNodes {

        @XmlElement(name = "cMSNavigationNode")
        protected List<CmsNavigationNodeDTO> cmsNavigationNode;

        /**
         * Gets the value of the cmsNavigationNode property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cmsNavigationNode property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCMSNavigationNode().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CmsNavigationNodeDTO }
         * 
         * 
         */
        public List<CmsNavigationNodeDTO> getCMSNavigationNode() {
            if (cmsNavigationNode == null) {
                cmsNavigationNode = new ArrayList<CmsNavigationNodeDTO>();
            }
            return this.cmsNavigationNode;
        }

    }

}
