//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for gridElementDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="gridElementDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}itemDTO">
 *       &lt;sequence>
 *         &lt;element name="defaultLayoutTemplate" type="{}layoutTemplateDTO" minOccurs="0"/>
 *         &lt;element ref="{}grid" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="xpos" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="xsize" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="ypos" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="ysize" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gridElementDTO", propOrder = {
    "defaultLayoutTemplate",
    "grid",
    "id",
    "name",
    "xpos",
    "xsize",
    "ypos",
    "ysize"
})
public class GridElementDTO
    extends ItemDTO
{

    protected LayoutTemplateDTO defaultLayoutTemplate;
    protected GridDTO grid;
    protected Integer id;
    protected String name;
    protected Double xpos;
    protected Double xsize;
    protected Double ypos;
    protected Double ysize;

    /**
     * Gets the value of the defaultLayoutTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link LayoutTemplateDTO }
     *     
     */
    public LayoutTemplateDTO getDefaultLayoutTemplate() {
        return defaultLayoutTemplate;
    }

    /**
     * Sets the value of the defaultLayoutTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link LayoutTemplateDTO }
     *     
     */
    public void setDefaultLayoutTemplate(LayoutTemplateDTO value) {
        this.defaultLayoutTemplate = value;
    }

    /**
     * Gets the value of the grid property.
     * 
     * @return
     *     possible object is
     *     {@link GridDTO }
     *     
     */
    public GridDTO getGrid() {
        return grid;
    }

    /**
     * Sets the value of the grid property.
     * 
     * @param value
     *     allowed object is
     *     {@link GridDTO }
     *     
     */
    public void setGrid(GridDTO value) {
        this.grid = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the xpos property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getXpos() {
        return xpos;
    }

    /**
     * Sets the value of the xpos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setXpos(Double value) {
        this.xpos = value;
    }

    /**
     * Gets the value of the xsize property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getXsize() {
        return xsize;
    }

    /**
     * Sets the value of the xsize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setXsize(Double value) {
        this.xsize = value;
    }

    /**
     * Gets the value of the ypos property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getYpos() {
        return ypos;
    }

    /**
     * Sets the value of the ypos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setYpos(Double value) {
        this.ypos = value;
    }

    /**
     * Gets the value of the ysize property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getYsize() {
        return ysize;
    }

    /**
     * Sets the value of the ysize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setYsize(Double value) {
        this.ysize = value;
    }

}
