//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for inboxViewDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inboxViewDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}itemDTO">
 *       &lt;sequence>
 *         &lt;element name="action" type="{}workflowActionDTO" minOccurs="0"/>
 *         &lt;element name="actioncomment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="activated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}workflow" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inboxViewDTO", propOrder = {
    "action",
    "actioncomment",
    "activated",
    "status",
    "workflow"
})
public class InboxViewDTO
    extends ItemDTO
{

    protected WorkflowActionDTO action;
    protected String actioncomment;
    protected String activated;
    protected String status;
    protected WorkflowDTO workflow;

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link WorkflowActionDTO }
     *     
     */
    public WorkflowActionDTO getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkflowActionDTO }
     *     
     */
    public void setAction(WorkflowActionDTO value) {
        this.action = value;
    }

    /**
     * Gets the value of the actioncomment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActioncomment() {
        return actioncomment;
    }

    /**
     * Sets the value of the actioncomment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActioncomment(String value) {
        this.actioncomment = value;
    }

    /**
     * Gets the value of the activated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivated() {
        return activated;
    }

    /**
     * Sets the value of the activated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivated(String value) {
        this.activated = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the workflow property.
     * 
     * @return
     *     possible object is
     *     {@link WorkflowDTO }
     *     
     */
    public WorkflowDTO getWorkflow() {
        return workflow;
    }

    /**
     * Sets the value of the workflow property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkflowDTO }
     *     
     */
    public void setWorkflow(WorkflowDTO value) {
        this.workflow = value;
    }

}
