//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for jasperWidgetPreferencesDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="jasperWidgetPreferencesDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}dynamicWidgetPreferencesDTO">
 *       &lt;sequence>
 *         &lt;element name="report" type="{}jasperMediaDTO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "jasperWidgetPreferencesDTO", propOrder = {
    "report"
})
@XmlSeeAlso({
    BtgJasperWidgetPreferencesDTO.class
})
public class JasperWidgetPreferencesDTO
    extends DynamicWidgetPreferencesDTO
{

    protected JasperMediaDTO report;

    /**
     * Gets the value of the report property.
     * 
     * @return
     *     possible object is
     *     {@link JasperMediaDTO }
     *     
     */
    public JasperMediaDTO getReport() {
        return report;
    }

    /**
     * Sets the value of the report property.
     * 
     * @param value
     *     allowed object is
     *     {@link JasperMediaDTO }
     *     
     */
    public void setReport(JasperMediaDTO value) {
        this.report = value;
    }

}
