//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ldifGroupImportCronJobDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ldifGroupImportCronJobDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}mediaProcessCronJobDTO">
 *       &lt;sequence>
 *         &lt;element name="codeExecution" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="configFile" type="{}configurationMediaDTO" minOccurs="0"/>
 *         &lt;element name="destMedia" type="{}impExMediaDTO" minOccurs="0"/>
 *         &lt;element name="dumpMedia" type="{}impExMediaDTO" minOccurs="0"/>
 *         &lt;element name="importUsers" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ldapquery" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ldifFile" type="{}ldifMediaDTO" minOccurs="0"/>
 *         &lt;element name="resultfilter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="searchbase" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userResultfilter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userRootDN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userSearchFieldQualifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ldifGroupImportCronJobDTO", propOrder = {
    "codeExecution",
    "configFile",
    "destMedia",
    "dumpMedia",
    "importUsers",
    "ldapquery",
    "ldifFile",
    "resultfilter",
    "searchbase",
    "userResultfilter",
    "userRootDN",
    "userSearchFieldQualifier"
})
public class LdifGroupImportCronJobDTO
    extends MediaProcessCronJobDTO
{

    protected Boolean codeExecution;
    protected ConfigurationMediaDTO configFile;
    protected ImpExMediaDTO destMedia;
    protected ImpExMediaDTO dumpMedia;
    protected Boolean importUsers;
    protected String ldapquery;
    protected LdifMediaDTO ldifFile;
    protected String resultfilter;
    protected String searchbase;
    protected String userResultfilter;
    protected String userRootDN;
    protected String userSearchFieldQualifier;

    /**
     * Gets the value of the codeExecution property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCodeExecution() {
        return codeExecution;
    }

    /**
     * Sets the value of the codeExecution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCodeExecution(Boolean value) {
        this.codeExecution = value;
    }

    /**
     * Gets the value of the configFile property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigurationMediaDTO }
     *     
     */
    public ConfigurationMediaDTO getConfigFile() {
        return configFile;
    }

    /**
     * Sets the value of the configFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigurationMediaDTO }
     *     
     */
    public void setConfigFile(ConfigurationMediaDTO value) {
        this.configFile = value;
    }

    /**
     * Gets the value of the destMedia property.
     * 
     * @return
     *     possible object is
     *     {@link ImpExMediaDTO }
     *     
     */
    public ImpExMediaDTO getDestMedia() {
        return destMedia;
    }

    /**
     * Sets the value of the destMedia property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImpExMediaDTO }
     *     
     */
    public void setDestMedia(ImpExMediaDTO value) {
        this.destMedia = value;
    }

    /**
     * Gets the value of the dumpMedia property.
     * 
     * @return
     *     possible object is
     *     {@link ImpExMediaDTO }
     *     
     */
    public ImpExMediaDTO getDumpMedia() {
        return dumpMedia;
    }

    /**
     * Sets the value of the dumpMedia property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImpExMediaDTO }
     *     
     */
    public void setDumpMedia(ImpExMediaDTO value) {
        this.dumpMedia = value;
    }

    /**
     * Gets the value of the importUsers property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isImportUsers() {
        return importUsers;
    }

    /**
     * Sets the value of the importUsers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setImportUsers(Boolean value) {
        this.importUsers = value;
    }

    /**
     * Gets the value of the ldapquery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLdapquery() {
        return ldapquery;
    }

    /**
     * Sets the value of the ldapquery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLdapquery(String value) {
        this.ldapquery = value;
    }

    /**
     * Gets the value of the ldifFile property.
     * 
     * @return
     *     possible object is
     *     {@link LdifMediaDTO }
     *     
     */
    public LdifMediaDTO getLdifFile() {
        return ldifFile;
    }

    /**
     * Sets the value of the ldifFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link LdifMediaDTO }
     *     
     */
    public void setLdifFile(LdifMediaDTO value) {
        this.ldifFile = value;
    }

    /**
     * Gets the value of the resultfilter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultfilter() {
        return resultfilter;
    }

    /**
     * Sets the value of the resultfilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultfilter(String value) {
        this.resultfilter = value;
    }

    /**
     * Gets the value of the searchbase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchbase() {
        return searchbase;
    }

    /**
     * Sets the value of the searchbase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchbase(String value) {
        this.searchbase = value;
    }

    /**
     * Gets the value of the userResultfilter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserResultfilter() {
        return userResultfilter;
    }

    /**
     * Sets the value of the userResultfilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserResultfilter(String value) {
        this.userResultfilter = value;
    }

    /**
     * Gets the value of the userRootDN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserRootDN() {
        return userRootDN;
    }

    /**
     * Sets the value of the userRootDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserRootDN(String value) {
        this.userRootDN = value;
    }

    /**
     * Gets the value of the userSearchFieldQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserSearchFieldQualifier() {
        return userSearchFieldQualifier;
    }

    /**
     * Sets the value of the userSearchFieldQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserSearchFieldQualifier(String value) {
        this.userSearchFieldQualifier = value;
    }

}
