//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mobileReceiveAndSendItemActionDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mobileReceiveAndSendItemActionDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}mobileReceiveGenericActionDTO">
 *       &lt;sequence>
 *         &lt;element name="content" type="{}itemDTO" minOccurs="0"/>
 *         &lt;element name="deeplinkUrl" type="{}deeplinkUrlDTO" minOccurs="0"/>
 *         &lt;element name="isLink" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mobileReceiveAndSendItemActionDTO", propOrder = {
    "content",
    "deeplinkUrl",
    "isLink",
    "subject"
})
@XmlSeeAlso({
    MobileReceiveAndSendProductActionDTO.class,
    MobileReceiveAndSendCatalogActionDTO.class,
    MobileReceiveAndSendCategoryActionDTO.class,
    MobileReceiveAndSendPageActionDTO.class
})
public class MobileReceiveAndSendItemActionDTO
    extends MobileReceiveGenericActionDTO
{

    protected ItemDTO content;
    protected DeeplinkUrlDTO deeplinkUrl;
    protected Boolean isLink;
    protected String subject;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link ItemDTO }
     *     
     */
    public ItemDTO getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemDTO }
     *     
     */
    public void setContent(ItemDTO value) {
        this.content = value;
    }

    /**
     * Gets the value of the deeplinkUrl property.
     * 
     * @return
     *     possible object is
     *     {@link DeeplinkUrlDTO }
     *     
     */
    public DeeplinkUrlDTO getDeeplinkUrl() {
        return deeplinkUrl;
    }

    /**
     * Sets the value of the deeplinkUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeeplinkUrlDTO }
     *     
     */
    public void setDeeplinkUrl(DeeplinkUrlDTO value) {
        this.deeplinkUrl = value;
    }

    /**
     * Gets the value of the isLink property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsLink() {
        return isLink;
    }

    /**
     * Sets the value of the isLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsLink(Boolean value) {
        this.isLink = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubject(String value) {
        this.subject = value;
    }

}
