//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for moveMediaCronJobDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="moveMediaCronJobDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}cronJobDTO">
 *       &lt;sequence>
 *         &lt;element name="medias" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}media" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="movedMediasCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="targetFolder" type="{}mediaFolderDTO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "moveMediaCronJobDTO", propOrder = {
    "medias",
    "movedMediasCount",
    "targetFolder"
})
public class MoveMediaCronJobDTO
    extends CronJobDTO
{

    protected MoveMediaCronJobDTO.Medias medias;
    protected Integer movedMediasCount;
    protected MediaFolderDTO targetFolder;

    /**
     * Gets the value of the medias property.
     * 
     * @return
     *     possible object is
     *     {@link MoveMediaCronJobDTO.Medias }
     *     
     */
    public MoveMediaCronJobDTO.Medias getMedias() {
        return medias;
    }

    /**
     * Sets the value of the medias property.
     * 
     * @param value
     *     allowed object is
     *     {@link MoveMediaCronJobDTO.Medias }
     *     
     */
    public void setMedias(MoveMediaCronJobDTO.Medias value) {
        this.medias = value;
    }

    /**
     * Gets the value of the movedMediasCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMovedMediasCount() {
        return movedMediasCount;
    }

    /**
     * Sets the value of the movedMediasCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMovedMediasCount(Integer value) {
        this.movedMediasCount = value;
    }

    /**
     * Gets the value of the targetFolder property.
     * 
     * @return
     *     possible object is
     *     {@link MediaFolderDTO }
     *     
     */
    public MediaFolderDTO getTargetFolder() {
        return targetFolder;
    }

    /**
     * Sets the value of the targetFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaFolderDTO }
     *     
     */
    public void setTargetFolder(MediaFolderDTO value) {
        this.targetFolder = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}media" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "media"
    })
    public static class Medias {

        protected List<MediaDTO> media;

        /**
         * Gets the value of the media property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the media property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMedia().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MediaDTO }
         * 
         * 
         */
        public List<MediaDTO> getMedia() {
            if (media == null) {
                media = new ArrayList<MediaDTO>();
            }
            return this.media;
        }

    }

}
