//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for orderProcessDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="orderProcessDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}businessProcessDTO">
 *       &lt;sequence>
 *         &lt;element name="consignmentProcesses" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="consignmentProcess" type="{}consignmentProcessDTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}order" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orderProcessDTO", propOrder = {
    "consignmentProcesses",
    "order"
})
@XmlSeeAlso({
    B2BApprovalProcessDTO.class,
    OrderModificationProcessDTO.class
})
public class OrderProcessDTO
    extends BusinessProcessDTO
{

    protected OrderProcessDTO.ConsignmentProcesses consignmentProcesses;
    protected OrderDTO order;

    /**
     * Gets the value of the consignmentProcesses property.
     * 
     * @return
     *     possible object is
     *     {@link OrderProcessDTO.ConsignmentProcesses }
     *     
     */
    public OrderProcessDTO.ConsignmentProcesses getConsignmentProcesses() {
        return consignmentProcesses;
    }

    /**
     * Sets the value of the consignmentProcesses property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderProcessDTO.ConsignmentProcesses }
     *     
     */
    public void setConsignmentProcesses(OrderProcessDTO.ConsignmentProcesses value) {
        this.consignmentProcesses = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link OrderDTO }
     *     
     */
    public OrderDTO getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderDTO }
     *     
     */
    public void setOrder(OrderDTO value) {
        this.order = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="consignmentProcess" type="{}consignmentProcessDTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "consignmentProcess"
    })
    public static class ConsignmentProcesses {

        protected List<ConsignmentProcessDTO> consignmentProcess;

        /**
         * Gets the value of the consignmentProcess property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the consignmentProcess property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConsignmentProcess().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ConsignmentProcessDTO }
         * 
         * 
         */
        public List<ConsignmentProcessDTO> getConsignmentProcess() {
            if (consignmentProcess == null) {
                consignmentProcess = new ArrayList<ConsignmentProcessDTO>();
            }
            return this.consignmentProcess;
        }

    }

}
