//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for orderCancelConfigDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="orderCancelConfigDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}itemDTO">
 *       &lt;sequence>
 *         &lt;element name="cancelAfterWarehouseAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="completeCancelAfterShippingStartedAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="orderCancelAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="partialCancelAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="partialOrderEntryCancelAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="queuedOrderWaitingTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orderCancelConfigDTO", propOrder = {
    "cancelAfterWarehouseAllowed",
    "completeCancelAfterShippingStartedAllowed",
    "orderCancelAllowed",
    "partialCancelAllowed",
    "partialOrderEntryCancelAllowed",
    "queuedOrderWaitingTime"
})
public class OrderCancelConfigDTO
    extends ItemDTO
{

    protected boolean cancelAfterWarehouseAllowed;
    protected boolean completeCancelAfterShippingStartedAllowed;
    protected boolean orderCancelAllowed;
    protected boolean partialCancelAllowed;
    protected boolean partialOrderEntryCancelAllowed;
    protected int queuedOrderWaitingTime;

    /**
     * Gets the value of the cancelAfterWarehouseAllowed property.
     * 
     */
    public boolean isCancelAfterWarehouseAllowed() {
        return cancelAfterWarehouseAllowed;
    }

    /**
     * Sets the value of the cancelAfterWarehouseAllowed property.
     * 
     */
    public void setCancelAfterWarehouseAllowed(boolean value) {
        this.cancelAfterWarehouseAllowed = value;
    }

    /**
     * Gets the value of the completeCancelAfterShippingStartedAllowed property.
     * 
     */
    public boolean isCompleteCancelAfterShippingStartedAllowed() {
        return completeCancelAfterShippingStartedAllowed;
    }

    /**
     * Sets the value of the completeCancelAfterShippingStartedAllowed property.
     * 
     */
    public void setCompleteCancelAfterShippingStartedAllowed(boolean value) {
        this.completeCancelAfterShippingStartedAllowed = value;
    }

    /**
     * Gets the value of the orderCancelAllowed property.
     * 
     */
    public boolean isOrderCancelAllowed() {
        return orderCancelAllowed;
    }

    /**
     * Sets the value of the orderCancelAllowed property.
     * 
     */
    public void setOrderCancelAllowed(boolean value) {
        this.orderCancelAllowed = value;
    }

    /**
     * Gets the value of the partialCancelAllowed property.
     * 
     */
    public boolean isPartialCancelAllowed() {
        return partialCancelAllowed;
    }

    /**
     * Sets the value of the partialCancelAllowed property.
     * 
     */
    public void setPartialCancelAllowed(boolean value) {
        this.partialCancelAllowed = value;
    }

    /**
     * Gets the value of the partialOrderEntryCancelAllowed property.
     * 
     */
    public boolean isPartialOrderEntryCancelAllowed() {
        return partialOrderEntryCancelAllowed;
    }

    /**
     * Sets the value of the partialOrderEntryCancelAllowed property.
     * 
     */
    public void setPartialOrderEntryCancelAllowed(boolean value) {
        this.partialOrderEntryCancelAllowed = value;
    }

    /**
     * Gets the value of the queuedOrderWaitingTime property.
     * 
     */
    public int getQueuedOrderWaitingTime() {
        return queuedOrderWaitingTime;
    }

    /**
     * Sets the value of the queuedOrderWaitingTime property.
     * 
     */
    public void setQueuedOrderWaitingTime(int value) {
        this.queuedOrderWaitingTime = value;
    }

}
