//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parserPropertyDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="parserPropertyDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}itemDTO">
 *       &lt;sequence>
 *         &lt;element name="endExp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="parserClass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="translatorConfiguration" type="{}jaloTranslatorConfigurationDTO" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="startExp" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parserPropertyDTO", propOrder = {
    "endExp",
    "parserClass",
    "translatorConfiguration"
})
public class ParserPropertyDTO
    extends ItemDTO
{

    protected String endExp;
    protected String parserClass;
    protected JaloTranslatorConfigurationDTO translatorConfiguration;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "startExp")
    protected String startExp;

    /**
     * Gets the value of the endExp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndExp() {
        return endExp;
    }

    /**
     * Sets the value of the endExp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndExp(String value) {
        this.endExp = value;
    }

    /**
     * Gets the value of the parserClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParserClass() {
        return parserClass;
    }

    /**
     * Sets the value of the parserClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParserClass(String value) {
        this.parserClass = value;
    }

    /**
     * Gets the value of the translatorConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link JaloTranslatorConfigurationDTO }
     *     
     */
    public JaloTranslatorConfigurationDTO getTranslatorConfiguration() {
        return translatorConfiguration;
    }

    /**
     * Sets the value of the translatorConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaloTranslatorConfigurationDTO }
     *     
     */
    public void setTranslatorConfiguration(JaloTranslatorConfigurationDTO value) {
        this.translatorConfiguration = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the startExp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartExp() {
        return startExp;
    }

    /**
     * Sets the value of the startExp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartExp(String value) {
        this.startExp = value;
    }

}
