//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for previewDataDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="previewDataDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}itemDTO">
 *       &lt;sequence>
 *         &lt;element name="activeCatalogVersion" type="{}catalogVersionDTO" minOccurs="0"/>
 *         &lt;element name="activeSite" type="{}cmsSiteDTO" minOccurs="0"/>
 *         &lt;element name="catalogVersions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="catalogVersion" type="{}catalogVersionDTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}country" minOccurs="0"/>
 *         &lt;element name="editMode" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element ref="{}language" minOccurs="0"/>
 *         &lt;element name="liveEdit" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="page" type="{}abstractPageDTO" minOccurs="0"/>
 *         &lt;element name="previewCatalog" type="{}catalogDTO" minOccurs="0"/>
 *         &lt;element name="previewCategory" type="{}categoryDTO" minOccurs="0"/>
 *         &lt;element name="previewProduct" type="{}productDTO" minOccurs="0"/>
 *         &lt;element name="resourcePath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="uiExperience" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}user" minOccurs="0"/>
 *         &lt;element name="userGroup" type="{}userGroupDTO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "previewDataDTO", propOrder = {
    "activeCatalogVersion",
    "activeSite",
    "catalogVersions",
    "country",
    "editMode",
    "language",
    "liveEdit",
    "page",
    "previewCatalog",
    "previewCategory",
    "previewProduct",
    "resourcePath",
    "time",
    "uiExperience",
    "user",
    "userGroup"
})
public class PreviewDataDTO
    extends ItemDTO
{

    protected CatalogVersionDTO activeCatalogVersion;
    protected CmsSiteDTO activeSite;
    protected PreviewDataDTO.CatalogVersions catalogVersions;
    protected CountryDTO country;
    protected Boolean editMode;
    protected LanguageDTO language;
    protected Boolean liveEdit;
    protected AbstractPageDTO page;
    protected CatalogDTO previewCatalog;
    protected CategoryDTO previewCategory;
    protected ProductDTO previewProduct;
    protected String resourcePath;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar time;
    protected String uiExperience;
    protected UserDTO user;
    protected UserGroupDTO userGroup;

    /**
     * Gets the value of the activeCatalogVersion property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogVersionDTO }
     *     
     */
    public CatalogVersionDTO getActiveCatalogVersion() {
        return activeCatalogVersion;
    }

    /**
     * Sets the value of the activeCatalogVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogVersionDTO }
     *     
     */
    public void setActiveCatalogVersion(CatalogVersionDTO value) {
        this.activeCatalogVersion = value;
    }

    /**
     * Gets the value of the activeSite property.
     * 
     * @return
     *     possible object is
     *     {@link CmsSiteDTO }
     *     
     */
    public CmsSiteDTO getActiveSite() {
        return activeSite;
    }

    /**
     * Sets the value of the activeSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link CmsSiteDTO }
     *     
     */
    public void setActiveSite(CmsSiteDTO value) {
        this.activeSite = value;
    }

    /**
     * Gets the value of the catalogVersions property.
     * 
     * @return
     *     possible object is
     *     {@link PreviewDataDTO.CatalogVersions }
     *     
     */
    public PreviewDataDTO.CatalogVersions getCatalogVersions() {
        return catalogVersions;
    }

    /**
     * Sets the value of the catalogVersions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreviewDataDTO.CatalogVersions }
     *     
     */
    public void setCatalogVersions(PreviewDataDTO.CatalogVersions value) {
        this.catalogVersions = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link CountryDTO }
     *     
     */
    public CountryDTO getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryDTO }
     *     
     */
    public void setCountry(CountryDTO value) {
        this.country = value;
    }

    /**
     * Gets the value of the editMode property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEditMode() {
        return editMode;
    }

    /**
     * Sets the value of the editMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEditMode(Boolean value) {
        this.editMode = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageDTO }
     *     
     */
    public LanguageDTO getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageDTO }
     *     
     */
    public void setLanguage(LanguageDTO value) {
        this.language = value;
    }

    /**
     * Gets the value of the liveEdit property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLiveEdit() {
        return liveEdit;
    }

    /**
     * Sets the value of the liveEdit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLiveEdit(Boolean value) {
        this.liveEdit = value;
    }

    /**
     * Gets the value of the page property.
     * 
     * @return
     *     possible object is
     *     {@link AbstractPageDTO }
     *     
     */
    public AbstractPageDTO getPage() {
        return page;
    }

    /**
     * Sets the value of the page property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstractPageDTO }
     *     
     */
    public void setPage(AbstractPageDTO value) {
        this.page = value;
    }

    /**
     * Gets the value of the previewCatalog property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogDTO }
     *     
     */
    public CatalogDTO getPreviewCatalog() {
        return previewCatalog;
    }

    /**
     * Sets the value of the previewCatalog property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogDTO }
     *     
     */
    public void setPreviewCatalog(CatalogDTO value) {
        this.previewCatalog = value;
    }

    /**
     * Gets the value of the previewCategory property.
     * 
     * @return
     *     possible object is
     *     {@link CategoryDTO }
     *     
     */
    public CategoryDTO getPreviewCategory() {
        return previewCategory;
    }

    /**
     * Sets the value of the previewCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoryDTO }
     *     
     */
    public void setPreviewCategory(CategoryDTO value) {
        this.previewCategory = value;
    }

    /**
     * Gets the value of the previewProduct property.
     * 
     * @return
     *     possible object is
     *     {@link ProductDTO }
     *     
     */
    public ProductDTO getPreviewProduct() {
        return previewProduct;
    }

    /**
     * Sets the value of the previewProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductDTO }
     *     
     */
    public void setPreviewProduct(ProductDTO value) {
        this.previewProduct = value;
    }

    /**
     * Gets the value of the resourcePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourcePath() {
        return resourcePath;
    }

    /**
     * Sets the value of the resourcePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourcePath(String value) {
        this.resourcePath = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTime(XMLGregorianCalendar value) {
        this.time = value;
    }

    /**
     * Gets the value of the uiExperience property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUiExperience() {
        return uiExperience;
    }

    /**
     * Sets the value of the uiExperience property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUiExperience(String value) {
        this.uiExperience = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link UserDTO }
     *     
     */
    public UserDTO getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDTO }
     *     
     */
    public void setUser(UserDTO value) {
        this.user = value;
    }

    /**
     * Gets the value of the userGroup property.
     * 
     * @return
     *     possible object is
     *     {@link UserGroupDTO }
     *     
     */
    public UserGroupDTO getUserGroup() {
        return userGroup;
    }

    /**
     * Sets the value of the userGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserGroupDTO }
     *     
     */
    public void setUserGroup(UserGroupDTO value) {
        this.userGroup = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="catalogVersion" type="{}catalogVersionDTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "catalogVersion"
    })
    public static class CatalogVersions {

        protected List<CatalogVersionDTO> catalogVersion;

        /**
         * Gets the value of the catalogVersion property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the catalogVersion property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCatalogVersion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CatalogVersionDTO }
         * 
         * 
         */
        public List<CatalogVersionDTO> getCatalogVersion() {
            if (catalogVersion == null) {
                catalogVersion = new ArrayList<CatalogVersionDTO>();
            }
            return this.catalogVersion;
        }

    }

}
