//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for productUpdateVersionDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="productUpdateVersionDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}itemDTO">
 *       &lt;sequence>
 *         &lt;element name="originalProduct" type="{}productDTO" minOccurs="0"/>
 *         &lt;element name="originalProductCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "productUpdateVersionDTO", propOrder = {
    "originalProduct",
    "originalProductCode"
})
public class ProductUpdateVersionDTO
    extends ItemDTO
{

    protected ProductDTO originalProduct;
    protected String originalProductCode;

    /**
     * Gets the value of the originalProduct property.
     * 
     * @return
     *     possible object is
     *     {@link ProductDTO }
     *     
     */
    public ProductDTO getOriginalProduct() {
        return originalProduct;
    }

    /**
     * Sets the value of the originalProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductDTO }
     *     
     */
    public void setOriginalProduct(ProductDTO value) {
        this.originalProduct = value;
    }

    /**
     * Gets the value of the originalProductCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalProductCode() {
        return originalProductCode;
    }

    /**
     * Sets the value of the originalProductCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalProductCode(String value) {
        this.originalProductCode = value;
    }

}
