//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for savedValueEntryDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="savedValueEntryDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}itemDTO">
 *       &lt;sequence>
 *         &lt;element name="modifiedAttribute" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="newValue" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="oldValue" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="oldValueAttributeDescriptor" type="{}attributeDescriptorDTO" minOccurs="0"/>
 *         &lt;element name="parent" type="{}savedValuesDTO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "savedValueEntryDTO", propOrder = {
    "modifiedAttribute",
    "newValue",
    "oldValue",
    "oldValueAttributeDescriptor",
    "parent"
})
public class SavedValueEntryDTO
    extends ItemDTO
{

    protected String modifiedAttribute;
    protected Object newValue;
    protected Object oldValue;
    protected AttributeDescriptorDTO oldValueAttributeDescriptor;
    protected SavedValuesDTO parent;

    /**
     * Gets the value of the modifiedAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedAttribute() {
        return modifiedAttribute;
    }

    /**
     * Sets the value of the modifiedAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedAttribute(String value) {
        this.modifiedAttribute = value;
    }

    /**
     * Gets the value of the newValue property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNewValue() {
        return newValue;
    }

    /**
     * Sets the value of the newValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNewValue(Object value) {
        this.newValue = value;
    }

    /**
     * Gets the value of the oldValue property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getOldValue() {
        return oldValue;
    }

    /**
     * Sets the value of the oldValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setOldValue(Object value) {
        this.oldValue = value;
    }

    /**
     * Gets the value of the oldValueAttributeDescriptor property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeDescriptorDTO }
     *     
     */
    public AttributeDescriptorDTO getOldValueAttributeDescriptor() {
        return oldValueAttributeDescriptor;
    }

    /**
     * Sets the value of the oldValueAttributeDescriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeDescriptorDTO }
     *     
     */
    public void setOldValueAttributeDescriptor(AttributeDescriptorDTO value) {
        this.oldValueAttributeDescriptor = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link SavedValuesDTO }
     *     
     */
    public SavedValuesDTO getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link SavedValuesDTO }
     *     
     */
    public void setParent(SavedValuesDTO value) {
        this.parent = value;
    }

}
