//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for solrFacetSearchConfigDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="solrFacetSearchConfigDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}itemDTO">
 *       &lt;sequence>
 *         &lt;element name="catalogVersions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="catalogVersion" type="{}catalogVersionDTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="currencies" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}currency" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="document" type="{}mediaDTO" minOccurs="0"/>
 *         &lt;element name="enabledLanguageFallbackMechanism" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="indexNamePrefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="keywordRedirects" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="solrFacetSearchKeywordRedirect" type="{}solrFacetSearchKeywordRedirectDTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="languageKeywordRedirectMapping" type="{}solrFacetSearchKeywordRedirectDTO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="languageStopWordMapping" type="{}solrStopWordDTO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="languageSynonymMapping" type="{}solrSynonymConfigDTO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="languages" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}language" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="solrIndexConfig" type="{}solrIndexConfigDTO" minOccurs="0"/>
 *         &lt;element name="solrIndexedTypes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="solrIndexedType" type="{}solrIndexedTypeDTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="solrIndexerCronJob" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="solrIndexerCronJob" type="{}solrIndexerCronJobDTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="solrSearchConfig" type="{}solrSearchConfigDTO" minOccurs="0"/>
 *         &lt;element name="solrServerConfig" type="{}solrServerConfigDTO" minOccurs="0"/>
 *         &lt;element name="solrUpdateStopWordsCronJobs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="solrUpdateStopWordsCronJob" type="{}solrUpdateStopWordsCronJobDTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="solrUpdateSynonymsCronJobs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="solrUpdateSynonymsCronJob" type="{}solrUpdateSynonymsCronJobDTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="solrValueRangeSets" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="solrValueRangeSet" type="{}solrValueRangeSetDTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="StopWords" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="solrStopWord" type="{}solrStopWordDTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="synonyms" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="solrSynonymConfig" type="{}solrSynonymConfigDTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "solrFacetSearchConfigDTO", propOrder = {
    "catalogVersions",
    "currencies",
    "description",
    "document",
    "enabledLanguageFallbackMechanism",
    "indexNamePrefix",
    "keywordRedirects",
    "languageKeywordRedirectMapping",
    "languageStopWordMapping",
    "languageSynonymMapping",
    "languages",
    "solrIndexConfig",
    "solrIndexedTypes",
    "solrIndexerCronJob",
    "solrSearchConfig",
    "solrServerConfig",
    "solrUpdateStopWordsCronJobs",
    "solrUpdateSynonymsCronJobs",
    "solrValueRangeSets",
    "stopWords",
    "synonyms"
})
public class SolrFacetSearchConfigDTO
    extends ItemDTO
{

    protected SolrFacetSearchConfigDTO.CatalogVersions catalogVersions;
    protected SolrFacetSearchConfigDTO.Currencies currencies;
    protected String description;
    protected MediaDTO document;
    protected boolean enabledLanguageFallbackMechanism;
    protected String indexNamePrefix;
    protected SolrFacetSearchConfigDTO.KeywordRedirects keywordRedirects;
    @XmlElement(nillable = true)
    protected List<SolrFacetSearchKeywordRedirectDTO> languageKeywordRedirectMapping;
    @XmlElement(nillable = true)
    protected List<SolrStopWordDTO> languageStopWordMapping;
    @XmlElement(nillable = true)
    protected List<SolrSynonymConfigDTO> languageSynonymMapping;
    protected SolrFacetSearchConfigDTO.Languages languages;
    protected SolrIndexConfigDTO solrIndexConfig;
    protected SolrFacetSearchConfigDTO.SolrIndexedTypes solrIndexedTypes;
    protected SolrFacetSearchConfigDTO.SolrIndexerCronJob solrIndexerCronJob;
    protected SolrSearchConfigDTO solrSearchConfig;
    protected SolrServerConfigDTO solrServerConfig;
    protected SolrFacetSearchConfigDTO.SolrUpdateStopWordsCronJobs solrUpdateStopWordsCronJobs;
    protected SolrFacetSearchConfigDTO.SolrUpdateSynonymsCronJobs solrUpdateSynonymsCronJobs;
    protected SolrFacetSearchConfigDTO.SolrValueRangeSets solrValueRangeSets;
    @XmlElement(name = "StopWords")
    protected SolrFacetSearchConfigDTO.StopWords stopWords;
    protected SolrFacetSearchConfigDTO.Synonyms synonyms;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the catalogVersions property.
     * 
     * @return
     *     possible object is
     *     {@link SolrFacetSearchConfigDTO.CatalogVersions }
     *     
     */
    public SolrFacetSearchConfigDTO.CatalogVersions getCatalogVersions() {
        return catalogVersions;
    }

    /**
     * Sets the value of the catalogVersions property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolrFacetSearchConfigDTO.CatalogVersions }
     *     
     */
    public void setCatalogVersions(SolrFacetSearchConfigDTO.CatalogVersions value) {
        this.catalogVersions = value;
    }

    /**
     * Gets the value of the currencies property.
     * 
     * @return
     *     possible object is
     *     {@link SolrFacetSearchConfigDTO.Currencies }
     *     
     */
    public SolrFacetSearchConfigDTO.Currencies getCurrencies() {
        return currencies;
    }

    /**
     * Sets the value of the currencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolrFacetSearchConfigDTO.Currencies }
     *     
     */
    public void setCurrencies(SolrFacetSearchConfigDTO.Currencies value) {
        this.currencies = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the document property.
     * 
     * @return
     *     possible object is
     *     {@link MediaDTO }
     *     
     */
    public MediaDTO getDocument() {
        return document;
    }

    /**
     * Sets the value of the document property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaDTO }
     *     
     */
    public void setDocument(MediaDTO value) {
        this.document = value;
    }

    /**
     * Gets the value of the enabledLanguageFallbackMechanism property.
     * 
     */
    public boolean isEnabledLanguageFallbackMechanism() {
        return enabledLanguageFallbackMechanism;
    }

    /**
     * Sets the value of the enabledLanguageFallbackMechanism property.
     * 
     */
    public void setEnabledLanguageFallbackMechanism(boolean value) {
        this.enabledLanguageFallbackMechanism = value;
    }

    /**
     * Gets the value of the indexNamePrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndexNamePrefix() {
        return indexNamePrefix;
    }

    /**
     * Sets the value of the indexNamePrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndexNamePrefix(String value) {
        this.indexNamePrefix = value;
    }

    /**
     * Gets the value of the keywordRedirects property.
     * 
     * @return
     *     possible object is
     *     {@link SolrFacetSearchConfigDTO.KeywordRedirects }
     *     
     */
    public SolrFacetSearchConfigDTO.KeywordRedirects getKeywordRedirects() {
        return keywordRedirects;
    }

    /**
     * Sets the value of the keywordRedirects property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolrFacetSearchConfigDTO.KeywordRedirects }
     *     
     */
    public void setKeywordRedirects(SolrFacetSearchConfigDTO.KeywordRedirects value) {
        this.keywordRedirects = value;
    }

    /**
     * Gets the value of the languageKeywordRedirectMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the languageKeywordRedirectMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguageKeywordRedirectMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SolrFacetSearchKeywordRedirectDTO }
     * 
     * 
     */
    public List<SolrFacetSearchKeywordRedirectDTO> getLanguageKeywordRedirectMapping() {
        if (languageKeywordRedirectMapping == null) {
            languageKeywordRedirectMapping = new ArrayList<SolrFacetSearchKeywordRedirectDTO>();
        }
        return this.languageKeywordRedirectMapping;
    }

    /**
     * Gets the value of the languageStopWordMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the languageStopWordMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguageStopWordMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SolrStopWordDTO }
     * 
     * 
     */
    public List<SolrStopWordDTO> getLanguageStopWordMapping() {
        if (languageStopWordMapping == null) {
            languageStopWordMapping = new ArrayList<SolrStopWordDTO>();
        }
        return this.languageStopWordMapping;
    }

    /**
     * Gets the value of the languageSynonymMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the languageSynonymMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguageSynonymMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SolrSynonymConfigDTO }
     * 
     * 
     */
    public List<SolrSynonymConfigDTO> getLanguageSynonymMapping() {
        if (languageSynonymMapping == null) {
            languageSynonymMapping = new ArrayList<SolrSynonymConfigDTO>();
        }
        return this.languageSynonymMapping;
    }

    /**
     * Gets the value of the languages property.
     * 
     * @return
     *     possible object is
     *     {@link SolrFacetSearchConfigDTO.Languages }
     *     
     */
    public SolrFacetSearchConfigDTO.Languages getLanguages() {
        return languages;
    }

    /**
     * Sets the value of the languages property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolrFacetSearchConfigDTO.Languages }
     *     
     */
    public void setLanguages(SolrFacetSearchConfigDTO.Languages value) {
        this.languages = value;
    }

    /**
     * Gets the value of the solrIndexConfig property.
     * 
     * @return
     *     possible object is
     *     {@link SolrIndexConfigDTO }
     *     
     */
    public SolrIndexConfigDTO getSolrIndexConfig() {
        return solrIndexConfig;
    }

    /**
     * Sets the value of the solrIndexConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolrIndexConfigDTO }
     *     
     */
    public void setSolrIndexConfig(SolrIndexConfigDTO value) {
        this.solrIndexConfig = value;
    }

    /**
     * Gets the value of the solrIndexedTypes property.
     * 
     * @return
     *     possible object is
     *     {@link SolrFacetSearchConfigDTO.SolrIndexedTypes }
     *     
     */
    public SolrFacetSearchConfigDTO.SolrIndexedTypes getSolrIndexedTypes() {
        return solrIndexedTypes;
    }

    /**
     * Sets the value of the solrIndexedTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolrFacetSearchConfigDTO.SolrIndexedTypes }
     *     
     */
    public void setSolrIndexedTypes(SolrFacetSearchConfigDTO.SolrIndexedTypes value) {
        this.solrIndexedTypes = value;
    }

    /**
     * Gets the value of the solrIndexerCronJob property.
     * 
     * @return
     *     possible object is
     *     {@link SolrFacetSearchConfigDTO.SolrIndexerCronJob }
     *     
     */
    public SolrFacetSearchConfigDTO.SolrIndexerCronJob getSolrIndexerCronJob() {
        return solrIndexerCronJob;
    }

    /**
     * Sets the value of the solrIndexerCronJob property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolrFacetSearchConfigDTO.SolrIndexerCronJob }
     *     
     */
    public void setSolrIndexerCronJob(SolrFacetSearchConfigDTO.SolrIndexerCronJob value) {
        this.solrIndexerCronJob = value;
    }

    /**
     * Gets the value of the solrSearchConfig property.
     * 
     * @return
     *     possible object is
     *     {@link SolrSearchConfigDTO }
     *     
     */
    public SolrSearchConfigDTO getSolrSearchConfig() {
        return solrSearchConfig;
    }

    /**
     * Sets the value of the solrSearchConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolrSearchConfigDTO }
     *     
     */
    public void setSolrSearchConfig(SolrSearchConfigDTO value) {
        this.solrSearchConfig = value;
    }

    /**
     * Gets the value of the solrServerConfig property.
     * 
     * @return
     *     possible object is
     *     {@link SolrServerConfigDTO }
     *     
     */
    public SolrServerConfigDTO getSolrServerConfig() {
        return solrServerConfig;
    }

    /**
     * Sets the value of the solrServerConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolrServerConfigDTO }
     *     
     */
    public void setSolrServerConfig(SolrServerConfigDTO value) {
        this.solrServerConfig = value;
    }

    /**
     * Gets the value of the solrUpdateStopWordsCronJobs property.
     * 
     * @return
     *     possible object is
     *     {@link SolrFacetSearchConfigDTO.SolrUpdateStopWordsCronJobs }
     *     
     */
    public SolrFacetSearchConfigDTO.SolrUpdateStopWordsCronJobs getSolrUpdateStopWordsCronJobs() {
        return solrUpdateStopWordsCronJobs;
    }

    /**
     * Sets the value of the solrUpdateStopWordsCronJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolrFacetSearchConfigDTO.SolrUpdateStopWordsCronJobs }
     *     
     */
    public void setSolrUpdateStopWordsCronJobs(SolrFacetSearchConfigDTO.SolrUpdateStopWordsCronJobs value) {
        this.solrUpdateStopWordsCronJobs = value;
    }

    /**
     * Gets the value of the solrUpdateSynonymsCronJobs property.
     * 
     * @return
     *     possible object is
     *     {@link SolrFacetSearchConfigDTO.SolrUpdateSynonymsCronJobs }
     *     
     */
    public SolrFacetSearchConfigDTO.SolrUpdateSynonymsCronJobs getSolrUpdateSynonymsCronJobs() {
        return solrUpdateSynonymsCronJobs;
    }

    /**
     * Sets the value of the solrUpdateSynonymsCronJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolrFacetSearchConfigDTO.SolrUpdateSynonymsCronJobs }
     *     
     */
    public void setSolrUpdateSynonymsCronJobs(SolrFacetSearchConfigDTO.SolrUpdateSynonymsCronJobs value) {
        this.solrUpdateSynonymsCronJobs = value;
    }

    /**
     * Gets the value of the solrValueRangeSets property.
     * 
     * @return
     *     possible object is
     *     {@link SolrFacetSearchConfigDTO.SolrValueRangeSets }
     *     
     */
    public SolrFacetSearchConfigDTO.SolrValueRangeSets getSolrValueRangeSets() {
        return solrValueRangeSets;
    }

    /**
     * Sets the value of the solrValueRangeSets property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolrFacetSearchConfigDTO.SolrValueRangeSets }
     *     
     */
    public void setSolrValueRangeSets(SolrFacetSearchConfigDTO.SolrValueRangeSets value) {
        this.solrValueRangeSets = value;
    }

    /**
     * Gets the value of the stopWords property.
     * 
     * @return
     *     possible object is
     *     {@link SolrFacetSearchConfigDTO.StopWords }
     *     
     */
    public SolrFacetSearchConfigDTO.StopWords getStopWords() {
        return stopWords;
    }

    /**
     * Sets the value of the stopWords property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolrFacetSearchConfigDTO.StopWords }
     *     
     */
    public void setStopWords(SolrFacetSearchConfigDTO.StopWords value) {
        this.stopWords = value;
    }

    /**
     * Gets the value of the synonyms property.
     * 
     * @return
     *     possible object is
     *     {@link SolrFacetSearchConfigDTO.Synonyms }
     *     
     */
    public SolrFacetSearchConfigDTO.Synonyms getSynonyms() {
        return synonyms;
    }

    /**
     * Sets the value of the synonyms property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolrFacetSearchConfigDTO.Synonyms }
     *     
     */
    public void setSynonyms(SolrFacetSearchConfigDTO.Synonyms value) {
        this.synonyms = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="catalogVersion" type="{}catalogVersionDTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "catalogVersion"
    })
    public static class CatalogVersions {

        protected List<CatalogVersionDTO> catalogVersion;

        /**
         * Gets the value of the catalogVersion property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the catalogVersion property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCatalogVersion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CatalogVersionDTO }
         * 
         * 
         */
        public List<CatalogVersionDTO> getCatalogVersion() {
            if (catalogVersion == null) {
                catalogVersion = new ArrayList<CatalogVersionDTO>();
            }
            return this.catalogVersion;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}currency" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "currency"
    })
    public static class Currencies {

        protected List<CurrencyDTO> currency;

        /**
         * Gets the value of the currency property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the currency property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCurrency().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CurrencyDTO }
         * 
         * 
         */
        public List<CurrencyDTO> getCurrency() {
            if (currency == null) {
                currency = new ArrayList<CurrencyDTO>();
            }
            return this.currency;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="solrFacetSearchKeywordRedirect" type="{}solrFacetSearchKeywordRedirectDTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "solrFacetSearchKeywordRedirect"
    })
    public static class KeywordRedirects {

        protected List<SolrFacetSearchKeywordRedirectDTO> solrFacetSearchKeywordRedirect;

        /**
         * Gets the value of the solrFacetSearchKeywordRedirect property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the solrFacetSearchKeywordRedirect property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSolrFacetSearchKeywordRedirect().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SolrFacetSearchKeywordRedirectDTO }
         * 
         * 
         */
        public List<SolrFacetSearchKeywordRedirectDTO> getSolrFacetSearchKeywordRedirect() {
            if (solrFacetSearchKeywordRedirect == null) {
                solrFacetSearchKeywordRedirect = new ArrayList<SolrFacetSearchKeywordRedirectDTO>();
            }
            return this.solrFacetSearchKeywordRedirect;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}language" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "language"
    })
    public static class Languages {

        protected List<LanguageDTO> language;

        /**
         * Gets the value of the language property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the language property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLanguage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LanguageDTO }
         * 
         * 
         */
        public List<LanguageDTO> getLanguage() {
            if (language == null) {
                language = new ArrayList<LanguageDTO>();
            }
            return this.language;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="solrIndexedType" type="{}solrIndexedTypeDTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "solrIndexedType"
    })
    public static class SolrIndexedTypes {

        protected List<SolrIndexedTypeDTO> solrIndexedType;

        /**
         * Gets the value of the solrIndexedType property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the solrIndexedType property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSolrIndexedType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SolrIndexedTypeDTO }
         * 
         * 
         */
        public List<SolrIndexedTypeDTO> getSolrIndexedType() {
            if (solrIndexedType == null) {
                solrIndexedType = new ArrayList<SolrIndexedTypeDTO>();
            }
            return this.solrIndexedType;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="solrIndexerCronJob" type="{}solrIndexerCronJobDTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "solrIndexerCronJob"
    })
    public static class SolrIndexerCronJob {

        protected List<SolrIndexerCronJobDTO> solrIndexerCronJob;

        /**
         * Gets the value of the solrIndexerCronJob property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the solrIndexerCronJob property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSolrIndexerCronJob().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SolrIndexerCronJobDTO }
         * 
         * 
         */
        public List<SolrIndexerCronJobDTO> getSolrIndexerCronJob() {
            if (solrIndexerCronJob == null) {
                solrIndexerCronJob = new ArrayList<SolrIndexerCronJobDTO>();
            }
            return this.solrIndexerCronJob;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="solrUpdateStopWordsCronJob" type="{}solrUpdateStopWordsCronJobDTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "solrUpdateStopWordsCronJob"
    })
    public static class SolrUpdateStopWordsCronJobs {

        protected List<SolrUpdateStopWordsCronJobDTO> solrUpdateStopWordsCronJob;

        /**
         * Gets the value of the solrUpdateStopWordsCronJob property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the solrUpdateStopWordsCronJob property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSolrUpdateStopWordsCronJob().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SolrUpdateStopWordsCronJobDTO }
         * 
         * 
         */
        public List<SolrUpdateStopWordsCronJobDTO> getSolrUpdateStopWordsCronJob() {
            if (solrUpdateStopWordsCronJob == null) {
                solrUpdateStopWordsCronJob = new ArrayList<SolrUpdateStopWordsCronJobDTO>();
            }
            return this.solrUpdateStopWordsCronJob;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="solrUpdateSynonymsCronJob" type="{}solrUpdateSynonymsCronJobDTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "solrUpdateSynonymsCronJob"
    })
    public static class SolrUpdateSynonymsCronJobs {

        protected List<SolrUpdateSynonymsCronJobDTO> solrUpdateSynonymsCronJob;

        /**
         * Gets the value of the solrUpdateSynonymsCronJob property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the solrUpdateSynonymsCronJob property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSolrUpdateSynonymsCronJob().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SolrUpdateSynonymsCronJobDTO }
         * 
         * 
         */
        public List<SolrUpdateSynonymsCronJobDTO> getSolrUpdateSynonymsCronJob() {
            if (solrUpdateSynonymsCronJob == null) {
                solrUpdateSynonymsCronJob = new ArrayList<SolrUpdateSynonymsCronJobDTO>();
            }
            return this.solrUpdateSynonymsCronJob;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="solrValueRangeSet" type="{}solrValueRangeSetDTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "solrValueRangeSet"
    })
    public static class SolrValueRangeSets {

        protected List<SolrValueRangeSetDTO> solrValueRangeSet;

        /**
         * Gets the value of the solrValueRangeSet property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the solrValueRangeSet property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSolrValueRangeSet().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SolrValueRangeSetDTO }
         * 
         * 
         */
        public List<SolrValueRangeSetDTO> getSolrValueRangeSet() {
            if (solrValueRangeSet == null) {
                solrValueRangeSet = new ArrayList<SolrValueRangeSetDTO>();
            }
            return this.solrValueRangeSet;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="solrStopWord" type="{}solrStopWordDTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "solrStopWord"
    })
    public static class StopWords {

        protected List<SolrStopWordDTO> solrStopWord;

        /**
         * Gets the value of the solrStopWord property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the solrStopWord property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSolrStopWord().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SolrStopWordDTO }
         * 
         * 
         */
        public List<SolrStopWordDTO> getSolrStopWord() {
            if (solrStopWord == null) {
                solrStopWord = new ArrayList<SolrStopWordDTO>();
            }
            return this.solrStopWord;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="solrSynonymConfig" type="{}solrSynonymConfigDTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "solrSynonymConfig"
    })
    public static class Synonyms {

        protected List<SolrSynonymConfigDTO> solrSynonymConfig;

        /**
         * Gets the value of the solrSynonymConfig property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the solrSynonymConfig property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSolrSynonymConfig().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SolrSynonymConfigDTO }
         * 
         * 
         */
        public List<SolrSynonymConfigDTO> getSolrSynonymConfig() {
            if (solrSynonymConfig == null) {
                solrSynonymConfig = new ArrayList<SolrSynonymConfigDTO>();
            }
            return this.solrSynonymConfig;
        }

    }

}
