//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.29 at 12:35:53 PM GMT 
//


package org.mule.modules.hybris.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for syncAttributeDescriptorConfigDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="syncAttributeDescriptorConfigDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}itemDTO">
 *       &lt;sequence>
 *         &lt;element name="attributeDescriptor" type="{}attributeDescriptorDTO" minOccurs="0"/>
 *         &lt;element name="copyByValue" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="includedInSync" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="presetValue" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="syncJob" type="{}syncItemJobDTO" minOccurs="0"/>
 *         &lt;element name="translateValue" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="untranslatable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "syncAttributeDescriptorConfigDTO", propOrder = {
    "attributeDescriptor",
    "copyByValue",
    "includedInSync",
    "presetValue",
    "syncJob",
    "translateValue",
    "untranslatable"
})
public class SyncAttributeDescriptorConfigDTO
    extends ItemDTO
{

    protected AttributeDescriptorDTO attributeDescriptor;
    protected Boolean copyByValue;
    protected Boolean includedInSync;
    protected Object presetValue;
    protected SyncItemJobDTO syncJob;
    protected Boolean translateValue;
    protected Boolean untranslatable;

    /**
     * Gets the value of the attributeDescriptor property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeDescriptorDTO }
     *     
     */
    public AttributeDescriptorDTO getAttributeDescriptor() {
        return attributeDescriptor;
    }

    /**
     * Sets the value of the attributeDescriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeDescriptorDTO }
     *     
     */
    public void setAttributeDescriptor(AttributeDescriptorDTO value) {
        this.attributeDescriptor = value;
    }

    /**
     * Gets the value of the copyByValue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCopyByValue() {
        return copyByValue;
    }

    /**
     * Sets the value of the copyByValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCopyByValue(Boolean value) {
        this.copyByValue = value;
    }

    /**
     * Gets the value of the includedInSync property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludedInSync() {
        return includedInSync;
    }

    /**
     * Sets the value of the includedInSync property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludedInSync(Boolean value) {
        this.includedInSync = value;
    }

    /**
     * Gets the value of the presetValue property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPresetValue() {
        return presetValue;
    }

    /**
     * Sets the value of the presetValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPresetValue(Object value) {
        this.presetValue = value;
    }

    /**
     * Gets the value of the syncJob property.
     * 
     * @return
     *     possible object is
     *     {@link SyncItemJobDTO }
     *     
     */
    public SyncItemJobDTO getSyncJob() {
        return syncJob;
    }

    /**
     * Sets the value of the syncJob property.
     * 
     * @param value
     *     allowed object is
     *     {@link SyncItemJobDTO }
     *     
     */
    public void setSyncJob(SyncItemJobDTO value) {
        this.syncJob = value;
    }

    /**
     * Gets the value of the translateValue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTranslateValue() {
        return translateValue;
    }

    /**
     * Sets the value of the translateValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTranslateValue(Boolean value) {
        this.translateValue = value;
    }

    /**
     * Gets the value of the untranslatable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUntranslatable() {
        return untranslatable;
    }

    /**
     * Sets the value of the untranslatable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUntranslatable(Boolean value) {
        this.untranslatable = value;
    }

}
